#!/bin/bash
# AUTHOR: Guillermo A. Perez
# DESCRIPTION: The post-processor for realizability tools on .ehoa benchmarks
#              (Based on Jens Kreber's script)
# arg1 = the solver's output (which StarExec saves to a file!, so this is a
#        a file path too)
# arg2 = the absolute path to the benchmark file

syntf="$1"
origf="$2"

if [ ! -f "$syntf" ]; then
    echo "Error=No output file found!"
    exit
fi
	
# Don't yet have tags for previous information
status="unknown"
echo "Expected_result=$status"

# Check realizability
if (grep -i -q $'.*\tUNREALIZABLE' "$syntf"); then  # the $'...'
    case "$status" in                               # results in \t being
	"realizable")                                   # correctly interpreted
        echo "Error=false negative"
	    exit 
	    ;;
	"unrealizable")
        echo "starexec-result=UNREALIZABLE"
	    exit
	    ;;
	"unknown")
        echo "starexec-result=NEW-UNREALIZABLE"
	    exit
	    ;;
	*)
	    echo "Error=Unknown status value"
	    exit
    esac
elif (grep -i -q $'.*\tREALIZABLE' "$syntf"); then
    case "$status" in
	"realizable")
        echo "starexec-result=REALIZABLE"
		exit
	    ;;
	"unrealizable")
        echo "Error=false positive"
	    exit 
	    ;;
	"unknown")
        echo "starexec-result=NEW-REALIZABLE"
		exit 
	    ;;
	*)
	    echo "Error=Unknown status value"
	    exit
    esac
fi

echo "Error=Found neither REALIZABLE nor UNREALIZABLE"
exit 
