#!/bin/bash
# AUTHOR: Guillermo A. Perez
# DESCRIPTION: The post-processor for realizability tools on .aag benchmarks
#              (Based on Jens Kreber's SyntVerify)
# arg1 = the solver's output (which StarExec saves to a file!, so this is a
#        a file path too)
# arg2 = the absolute path to the benchmark file

syntf="$1"
origf="$2"

if [ ! -f "$syntf" ]; then
    echo "Error=No output file found!"
    exit $NO_OUTPUT
fi

syntline=$(grep -n "^#!SYNTCOMP" "$origf" | head -n 1 | cut -d ':' -f 1)
if [ -z "$syntline" ]; then
	status="unknown"
else
    synttag=$(tail -n +$syntline "$origf")
    status=$(grep "STATUS[[:space:]]*:" <<< "$synttag" | cut -d ':' -f 2 | sed "s/ //g")
fi
echo "Expected_result=$status"

# Check realizability
if (grep -i -q $'.*\tUNREALIZABLE' "$syntf"); then  # the $'...'
    case "$status" in                               # results in \t being
	"realizable")                                   # correctly interpreted
        echo "starexec-result=false-negative"
	    exit 
	    ;;
	"unrealizable")
        echo "starexec-result=UNREALIZABLE"
	    exit
	    ;;
	"unknown")
        echo "starexec-result=NEW-UNREALIZABLE"
	    exit
	    ;;
	*)
	    echo "Error=Incorrect status value."
	    exit
    esac
elif (grep -i -q $'.*\tREALIZABLE' "$syntf"); then
    case "$status" in
	"realizable")
        echo "starexec-result=REALIZABLE"
		exit
	    ;;
	"unrealizable")
        echo "starexec-result=false-positive"
	    exit 
	    ;;
	"unknown")
        echo "starexec-result=NEW-REALIZABLE"
		exit 
	    ;;
	*)
	    echo "Error=Incorrect status value."
	    exit
    esac
fi

echo "Error=Found neither REALIZABLE nor UNREALIZABLE"
exit 
