#!/bin/bash
# AUTHOR: Guillermo A. Perez
# DESCRIPTION: The benchmark processor for .tlsf benchmarks
# arg1 = the absolute path to the benchmark file
 
# Here we perform basic validation: we call syfco on it & discard its output
./syfco $1 >/dev/null
exit_code=$?
if [[ $exit_code == 0 ]]; then
    echo "starexec-valid=true"

    # If the syntax is valid, we process the benchmark metadata
    python "print_metadata.py" $1
else
    echo "starexec-valid=false"
fi
