# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


"""
PyCUDD 2.0.3
Python interface to Colorado University Decision Diagram package
With BREL support
Copyright (c) 2014, The Regents of the University of California
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Compiled on May  1 2019, 07:24:39
Bugs to:forrest@ece.ucsb.edu
"""


from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pycudd', [dirname(__file__)])
        except ImportError:
            import _pycudd
            return _pycudd
        if fp is not None:
            try:
                _mod = imp.load_module('_pycudd', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pycudd = swig_import_helper()
    del swig_import_helper
else:
    import _pycudd
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


DOCSTRING = _pycudd.DOCSTRING
class RangeError(_object):
    """Proxy of C++ RangeError class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, RangeError, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RangeError, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(RangeError self) -> RangeError"""
        this = _pycudd.new_RangeError()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_RangeError
    __del__ = lambda self : None;
RangeError_swigregister = _pycudd.RangeError_swigregister
RangeError_swigregister(RangeError)
cvar = _pycudd.cvar

class IntArray(_object):
    """Proxy of C++ IntArray class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, IntArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntArray, name)
    __repr__ = _swig_repr
    __swig_setmethods__["vec"] = _pycudd.IntArray_vec_set
    __swig_getmethods__["vec"] = _pycudd.IntArray_vec_get
    if _newclass:vec = _swig_property(_pycudd.IntArray_vec_get, _pycudd.IntArray_vec_set)
    def __init__(self, *args): 
        """__init__(IntArray self, int size) -> IntArray"""
        this = _pycudd.new_IntArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_IntArray
    __del__ = lambda self : None;
    def AssignVect(self, *args):
        """AssignVect(IntArray self, int * str, int size)"""
        return _pycudd.IntArray_AssignVect(self, *args)

    def AssignComplVect(self, *args):
        """AssignComplVect(IntArray self, int * str, int size, int univ)"""
        return _pycudd.IntArray_AssignComplVect(self, *args)

    def ArrayAddress(self):
        """ArrayAddress(IntArray self) -> int **"""
        return _pycudd.IntArray_ArrayAddress(self)

    def __getitem__(self, *args):
        """__getitem__(IntArray self, int j) -> int"""
        return _pycudd.IntArray___getitem__(self, *args)

    def __setitem__(self, *args):
        """__setitem__(IntArray self, int j, int val)"""
        return _pycudd.IntArray___setitem__(self, *args)

    def __len__(self):
        """__len__(IntArray self) -> int"""
        return _pycudd.IntArray___len__(self)

    def Assign(self, *args):
        """Assign(IntArray self, int * list, int k)"""
        return _pycudd.IntArray_Assign(self, *args)

    def Swap(self, *args):
        """Swap(IntArray self, int i, int j)"""
        return _pycudd.IntArray_Swap(self, *args)

IntArray_swigregister = _pycudd.IntArray_swigregister
IntArray_swigregister(IntArray)

class StringArray(_object):
    """Proxy of C++ StringArray class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, StringArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringArray, name)
    __repr__ = _swig_repr
    __swig_setmethods__["vec"] = _pycudd.StringArray_vec_set
    __swig_getmethods__["vec"] = _pycudd.StringArray_vec_get
    if _newclass:vec = _swig_property(_pycudd.StringArray_vec_get, _pycudd.StringArray_vec_set)
    def __init__(self, *args): 
        """__init__(StringArray self, int size) -> StringArray"""
        this = _pycudd.new_StringArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_StringArray
    __del__ = lambda self : None;
    def ArrayAddress(self):
        """ArrayAddress(StringArray self) -> char ***"""
        return _pycudd.StringArray_ArrayAddress(self)

    def __getitem__(self, *args):
        """__getitem__(StringArray self, int j) -> char *"""
        return _pycudd.StringArray___getitem__(self, *args)

    def __setitem__(self, *args):
        """__setitem__(StringArray self, int j, char * val)"""
        return _pycudd.StringArray___setitem__(self, *args)

    def __len__(self):
        """__len__(StringArray self) -> int"""
        return _pycudd.StringArray___len__(self)

    def Assign(self, *args):
        """Assign(StringArray self, char ** list, int k)"""
        return _pycudd.StringArray_Assign(self, *args)

    def Swap(self, *args):
        """Swap(StringArray self, int i, int j)"""
        return _pycudd.StringArray_Swap(self, *args)

StringArray_swigregister = _pycudd.StringArray_swigregister
StringArray_swigregister(StringArray)

class DoubleArray(_object):
    """Proxy of C++ DoubleArray class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, DoubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleArray, name)
    __repr__ = _swig_repr
    __swig_setmethods__["vec"] = _pycudd.DoubleArray_vec_set
    __swig_getmethods__["vec"] = _pycudd.DoubleArray_vec_get
    if _newclass:vec = _swig_property(_pycudd.DoubleArray_vec_get, _pycudd.DoubleArray_vec_set)
    def __init__(self, *args): 
        """__init__(DoubleArray self, int size) -> DoubleArray"""
        this = _pycudd.new_DoubleArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_DoubleArray
    __del__ = lambda self : None;
    def __getitem__(self, *args):
        """__getitem__(DoubleArray self, int j) -> double"""
        return _pycudd.DoubleArray___getitem__(self, *args)

    def __setitem__(self, *args):
        """__setitem__(DoubleArray self, int j, double val)"""
        return _pycudd.DoubleArray___setitem__(self, *args)

    def Assign(self, *args):
        """Assign(DoubleArray self, double * list, int k)"""
        return _pycudd.DoubleArray_Assign(self, *args)

    def Swap(self, *args):
        """Swap(DoubleArray self, int i, int j)"""
        return _pycudd.DoubleArray_Swap(self, *args)

DoubleArray_swigregister = _pycudd.DoubleArray_swigregister
DoubleArray_swigregister(DoubleArray)

class DdArray(_object):
    """Proxy of C++ DdArray class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, DdArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DdArray, name)
    __repr__ = _swig_repr
    __doc__ = "This class provides an array of DdNodes. This is an addition to the CUDD package. Create a DdArray by calling the constructor with the length of the array. In terms of Python array-like behaviour, you can index it, assign individual elements and take its length. Typically, these arrays are populated via the Push method. Refer pycudd.h and pycudd.cpp for function details.<br>"

    __swig_setmethods__["sz"] = _pycudd.DdArray_sz_set
    __swig_getmethods__["sz"] = _pycudd.DdArray_sz_get
    if _newclass:sz = _swig_property(_pycudd.DdArray_sz_get, _pycudd.DdArray_sz_set)
    __swig_setmethods__["vec"] = _pycudd.DdArray_vec_set
    __swig_getmethods__["vec"] = _pycudd.DdArray_vec_get
    if _newclass:vec = _swig_property(_pycudd.DdArray_vec_get, _pycudd.DdArray_vec_set)
    def __init__(self, *args): 
        """__init__(DdArray self, int size) -> DdArray"""
        this = _pycudd.new_DdArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_DdArray
    __del__ = lambda self : None;
    def __getitem__(self, *args):
        """__getitem__(DdArray self, int j) -> DdNode"""
        return _pycudd.DdArray___getitem__(self, *args)

    def __setitem__(self, *args):
        """__setitem__(DdArray self, int j, DdNode val)"""
        return _pycudd.DdArray___setitem__(self, *args)

    def __len__(self):
        """__len__(DdArray self) -> int"""
        return _pycudd.DdArray___len__(self)

    def Swap(self, *args):
        """Swap(DdArray self, int i, int j)"""
        return _pycudd.DdArray_Swap(self, *args)

    def Pop(self):
        """Pop(DdArray self) -> DdNode"""
        return _pycudd.DdArray_Pop(self)

    def And(self):
        """And(DdArray self) -> DdNode"""
        return _pycudd.DdArray_And(self)

    def Or(self):
        """Or(DdArray self) -> DdNode"""
        return _pycudd.DdArray_Or(self)

    def AtLeastN(self, *args):
        """AtLeastN(DdArray self, int n) -> DdNode"""
        return _pycudd.DdArray_AtLeastN(self, *args)

    def ExactlyN(self, *args):
        """ExactlyN(DdArray self, int n) -> DdNode"""
        return _pycudd.DdArray_ExactlyN(self, *args)

    def UpToN(self, *args):
        """UpToN(DdArray self, int n) -> DdNode"""
        return _pycudd.DdArray_UpToN(self, *args)

    def Constraint(self, *args):
        """Constraint(DdArray self, int low, int high) -> DdNode"""
        return _pycudd.DdArray_Constraint(self, *args)

    def Compose(self, *args):
        """Compose(DdArray self, DdNode term) -> DdNode"""
        return _pycudd.DdArray_Compose(self, *args)

    def Assign(self, *args):
        """Assign(DdArray self, DdNode ** list, int k)"""
        return _pycudd.DdArray_Assign(self, *args)

    def Push(self, *args):
        """Push(DdArray self, DdNode val)"""
        return _pycudd.DdArray_Push(self, *args)

    def SwapNodes(self, *args):
        """SwapNodes(DdArray self, int i, int j)"""
        return _pycudd.DdArray_SwapNodes(self, *args)

    def Fill(self, *args):
        """Fill(DdArray self, int offset, int mod)"""
        return _pycudd.DdArray_Fill(self, *args)

    def FillWithIntArray(self, *args):
        """FillWithIntArray(DdArray self, IntArray t)"""
        return _pycudd.DdArray_FillWithIntArray(self, *args)

    def OrderVector(self, *args):
        """OrderVector(DdArray self, int left, int right)"""
        return _pycudd.DdArray_OrderVector(self, *args)

    def SupportVector(self, *args):
        """SupportVector(DdArray self, DdNode term)"""
        return _pycudd.DdArray_SupportVector(self, *args)

    def SetVarMap(self, *args):
        """SetVarMap(DdArray self, DdArray other) -> int"""
        return _pycudd.DdArray_SetVarMap(self, *args)

    def VectorSupport(self):
        """VectorSupport(DdArray self) -> DdNode"""
        return _pycudd.DdArray_VectorSupport(self)

    def VectorSupportIndex(self):
        """VectorSupportIndex(DdArray self) -> int"""
        return _pycudd.DdArray_VectorSupportIndex(self)

    def PickOneMinterm(self, *args):
        """PickOneMinterm(DdArray self, DdNode term) -> DdNode"""
        return _pycudd.DdArray_PickOneMinterm(self, *args)

    def HoldTR(self, *args):
        """HoldTR(DdArray self, DdArray other) -> DdNode"""
        return _pycudd.DdArray_HoldTR(self, *args)

    def Find(self, *args):
        """Find(DdArray self, DdNode term) -> int"""
        return _pycudd.DdArray_Find(self, *args)

    def Save(self, *args):
        """Save(DdArray self, char * filename) -> int"""
        return _pycudd.DdArray_Save(self, *args)

    def SaveText(self, *args):
        """SaveText(DdArray self, char * filename) -> int"""
        return _pycudd.DdArray_SaveText(self, *args)

    def Load(self, *args):
        """Load(DdArray self, char * filename) -> int"""
        return _pycudd.DdArray_Load(self, *args)

    def LoadText(self, *args):
        """LoadText(DdArray self, char * filename) -> int"""
        return _pycudd.DdArray_LoadText(self, *args)

    def ArrayLoad(self, *args):
        """
        ArrayLoad(DdArray self, int rootmatchmode, StringArray rootmatchnames, int varmatchmode, StringArray varmatchnames, 
            IntArray varmatchauxids, IntArray varcomposeids, int mode, char * filename, 
            FILE * fp=None) -> int
        ArrayLoad(DdArray self, int rootmatchmode, StringArray rootmatchnames, int varmatchmode, StringArray varmatchnames, 
            IntArray varmatchauxids, IntArray varcomposeids, int mode, char * filename) -> int
        """
        return _pycudd.DdArray_ArrayLoad(self, *args)

    def ArrayStore(self, *args):
        """
        ArrayStore(DdArray self, char * ddname, StringArray rootnames, StringArray varnames, IntArray auxids, int mode, 
            int varinfo, char * filename, FILE * fp=None) -> int
        ArrayStore(DdArray self, char * ddname, StringArray rootnames, StringArray varnames, IntArray auxids, int mode, 
            int varinfo, char * filename) -> int
        """
        return _pycudd.DdArray_ArrayStore(self, *args)

DdArray_swigregister = _pycudd.DdArray_swigregister
DdArray_swigregister(DdArray)

class MtrNode(_object):
    """Proxy of C++ MtrNode class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, MtrNode, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MtrNode, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(MtrNode self) -> MtrNode"""
        this = _pycudd.new_MtrNode()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_MtrNode
    __del__ = lambda self : None;
MtrNode_swigregister = _pycudd.MtrNode_swigregister
MtrNode_swigregister(MtrNode)

class DdTlcInfo(_object):
    """Proxy of C++ DdTlcInfo class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, DdTlcInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DdTlcInfo, name)
    __repr__ = _swig_repr
    __doc__ = "Helper class for enumeration of two literal clauses. Look at example2.py for usage."

    def __init__(self): 
        """__init__(DdTlcInfo self) -> DdTlcInfo"""
        this = _pycudd.new_DdTlcInfo()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_DdTlcInfo
    __del__ = lambda self : None;
    def ReadIthClause(self, *args):
        """ReadIthClause(DdTlcInfo self, int i) -> int"""
        return _pycudd.DdTlcInfo_ReadIthClause(self, *args)

DdTlcInfo_swigregister = _pycudd.DdTlcInfo_swigregister
DdTlcInfo_swigregister(DdTlcInfo)

class EpDouble(_object):
    """Proxy of C++ EpDouble class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, EpDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EpDouble, name)
    __repr__ = _swig_repr
    __doc__ = "This provides the functionality of CUDD's extended precision library. In particular, instances of EpDouble may be passed to DdNode.EpdCountMinterm to retrieve the extended counts. Note also that the basic arithmetic operators (+,-,*,/) have been overloaded for use with EpDouble instances"

    def __init__(self, *args): 
        """
        __init__(EpDouble self) -> EpDouble
        __init__(EpDouble self, double value) -> EpDouble
        __init__(EpDouble self, EpDouble value) -> EpDouble
        """
        this = _pycudd.new_EpDouble(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_EpDouble
    __del__ = lambda self : None;
    def EpdConvert(self, *args):
        """EpdConvert(EpDouble self, double value)"""
        return _pycudd.EpDouble_EpdConvert(self, *args)

    def EpdNormalize(self):
        """EpdNormalize(EpDouble self)"""
        return _pycudd.EpDouble_EpdNormalize(self)

    def EpdNormalizeDecimal(self):
        """EpdNormalizeDecimal(EpDouble self)"""
        return _pycudd.EpDouble_EpdNormalizeDecimal(self)

    def EpdMakeInf(self, *args):
        """EpdMakeInf(EpDouble self, int sign)"""
        return _pycudd.EpDouble_EpdMakeInf(self, *args)

    def EpdMakeZero(self, *args):
        """EpdMakeZero(EpDouble self, int sign)"""
        return _pycudd.EpDouble_EpdMakeZero(self, *args)

    def EpdMakeNan(self):
        """EpdMakeNan(EpDouble self)"""
        return _pycudd.EpDouble_EpdMakeNan(self)

    def EpdCopy(self, *args):
        """EpdCopy(EpDouble self, EpDouble to)"""
        return _pycudd.EpDouble_EpdCopy(self, *args)

    def EpdGetValueAndDecimalExponent(self):
        """EpdGetValueAndDecimalExponent(EpDouble self)"""
        return _pycudd.EpDouble_EpdGetValueAndDecimalExponent(self)

    def EpdMultiply(self, *args):
        """EpdMultiply(EpDouble self, double value)"""
        return _pycudd.EpDouble_EpdMultiply(self, *args)

    def EpdMultiply2(self, *args):
        """EpdMultiply2(EpDouble self, EpDouble epd2)"""
        return _pycudd.EpDouble_EpdMultiply2(self, *args)

    def EpdMultiply2Decimal(self, *args):
        """EpdMultiply2Decimal(EpDouble self, EpDouble epd2)"""
        return _pycudd.EpDouble_EpdMultiply2Decimal(self, *args)

    def EpdMultiply3(self, *args):
        """EpdMultiply3(EpDouble self, EpDouble epd2, EpDouble epd3)"""
        return _pycudd.EpDouble_EpdMultiply3(self, *args)

    def EpdMultiply3Decimal(self, *args):
        """EpdMultiply3Decimal(EpDouble self, EpDouble epd2, EpDouble epd3)"""
        return _pycudd.EpDouble_EpdMultiply3Decimal(self, *args)

    def EpdDivide(self, *args):
        """EpdDivide(EpDouble self, double value)"""
        return _pycudd.EpDouble_EpdDivide(self, *args)

    def EpdDivide2(self, *args):
        """EpdDivide2(EpDouble self, EpDouble epd2)"""
        return _pycudd.EpDouble_EpdDivide2(self, *args)

    def EpdDivide3(self, *args):
        """EpdDivide3(EpDouble self, EpDouble epd2, EpDouble epd3)"""
        return _pycudd.EpDouble_EpdDivide3(self, *args)

    def EpdAdd(self, *args):
        """EpdAdd(EpDouble self, double value)"""
        return _pycudd.EpDouble_EpdAdd(self, *args)

    def EpdAdd2(self, *args):
        """EpdAdd2(EpDouble self, EpDouble epd2)"""
        return _pycudd.EpDouble_EpdAdd2(self, *args)

    def EpdAdd3(self, *args):
        """EpdAdd3(EpDouble self, EpDouble epd2, EpDouble epd3)"""
        return _pycudd.EpDouble_EpdAdd3(self, *args)

    def EpdSubtract(self, *args):
        """EpdSubtract(EpDouble self, double value)"""
        return _pycudd.EpDouble_EpdSubtract(self, *args)

    def EpdSubtract2(self, *args):
        """EpdSubtract2(EpDouble self, EpDouble epd2)"""
        return _pycudd.EpDouble_EpdSubtract2(self, *args)

    def EpdSubtract3(self, *args):
        """EpdSubtract3(EpDouble self, EpDouble epd2, EpDouble epd3)"""
        return _pycudd.EpDouble_EpdSubtract3(self, *args)

    def EpdPow2(self, *args):
        """EpdPow2(EpDouble self, int n)"""
        return _pycudd.EpDouble_EpdPow2(self, *args)

    def EpdPow2Decimal(self, *args):
        """EpdPow2Decimal(EpDouble self, int n)"""
        return _pycudd.EpDouble_EpdPow2Decimal(self, *args)

    def __add__(self, *args):
        """
        __add__(EpDouble self, EpDouble other) -> EpDouble
        __add__(EpDouble self, double other) -> EpDouble
        """
        return _pycudd.EpDouble___add__(self, *args)

    def __sub__(self, *args):
        """
        __sub__(EpDouble self, EpDouble other) -> EpDouble
        __sub__(EpDouble self, double other) -> EpDouble
        """
        return _pycudd.EpDouble___sub__(self, *args)

    def __mul__(self, *args):
        """
        __mul__(EpDouble self, EpDouble other) -> EpDouble
        __mul__(EpDouble self, double other) -> EpDouble
        """
        return _pycudd.EpDouble___mul__(self, *args)

    def __div__(self, *args):
        """
        __div__(EpDouble self, EpDouble other) -> EpDouble
        __div__(EpDouble self, double other) -> EpDouble
        """
        return _pycudd.EpDouble___div__(self, *args)

    def EpdCmp(self, *args):
        """EpdCmp(EpDouble self, EpDouble other) -> bool"""
        return _pycudd.EpDouble_EpdCmp(self, *args)

    def EpdIsInf(self):
        """EpdIsInf(EpDouble self) -> bool"""
        return _pycudd.EpDouble_EpdIsInf(self)

    def EpdIsZero(self):
        """EpdIsZero(EpDouble self) -> bool"""
        return _pycudd.EpDouble_EpdIsZero(self)

    def EpdIsNan(self):
        """EpdIsNan(EpDouble self) -> bool"""
        return _pycudd.EpDouble_EpdIsNan(self)

    def EpdIsNanOrInf(self):
        """EpdIsNanOrInf(EpDouble self) -> bool"""
        return _pycudd.EpDouble_EpdIsNanOrInf(self)

    def __nonzero__(self):
        """__nonzero__(EpDouble self) -> bool"""
        return _pycudd.EpDouble___nonzero__(self)

    def __eq__(self, *args):
        """__eq__(EpDouble self, EpDouble other) -> bool"""
        return _pycudd.EpDouble___eq__(self, *args)

    def __ne__(self, *args):
        """__ne__(EpDouble self, EpDouble other) -> bool"""
        return _pycudd.EpDouble___ne__(self, *args)

EpDouble_swigregister = _pycudd.EpDouble_swigregister
EpDouble_swigregister(EpDouble)


def EpdGetExponent(*args):
  """EpdGetExponent(double value) -> int"""
  return _pycudd.EpdGetExponent(*args)

def EpdGetExponentDecimal(*args):
  """EpdGetExponentDecimal(double value) -> int"""
  return _pycudd.EpdGetExponentDecimal(*args)

def IsInfDouble(*args):
  """IsInfDouble(double value) -> bool"""
  return _pycudd.IsInfDouble(*args)

def IsNanDouble(*args):
  """IsNanDouble(double value) -> bool"""
  return _pycudd.IsNanDouble(*args)

def IsNanOrInfDouble(*args):
  """IsNanOrInfDouble(double value) -> bool"""
  return _pycudd.IsNanOrInfDouble(*args)
class DdManager(_object):
    """Proxy of C++ DdManager class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, DdManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DdManager, name)
    __repr__ = _swig_repr
    __doc__ = "This class wraps around the DdManager. The methods defined by this class provide themselves as the DdManager option (if needed). To use PyCUDD, you must have at least one DdManager instance and you must set DdManager.SetDefault before using any of the other functions. These functions are provided through ddmanager.i."

    def __init__(self, *args): 
        """
        __init__(DdManager self, unsigned int numVars=0, unsigned int numVarsZ=0, unsigned int numSlots=CUDD_UNIQUE_SLOTS, 
            unsigned int cacheSize=CUDD_CACHE_SLOTS, unsigned long maxMemory=0) -> DdManager
        __init__(DdManager self, unsigned int numVars=0, unsigned int numVarsZ=0, unsigned int numSlots=CUDD_UNIQUE_SLOTS, 
            unsigned int cacheSize=CUDD_CACHE_SLOTS) -> DdManager
        __init__(DdManager self, unsigned int numVars=0, unsigned int numVarsZ=0, unsigned int numSlots=CUDD_UNIQUE_SLOTS) -> DdManager
        __init__(DdManager self, unsigned int numVars=0, unsigned int numVarsZ=0) -> DdManager
        __init__(DdManager self, unsigned int numVars=0) -> DdManager
        __init__(DdManager self) -> DdManager
        """
        this = _pycudd.new_DdManager(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_DdManager
    __del__ = lambda self : None;
    def KillNode(self, *args):
        """KillNode(DdManager self, long num)"""
        return _pycudd.DdManager_KillNode(self, *args)

    def IsPsVar(self, *args):
        """IsPsVar(DdManager self, int index) -> int"""
        return _pycudd.DdManager_IsPsVar(self, *args)

    def IsNsVar(self, *args):
        """IsNsVar(DdManager self, int index) -> int"""
        return _pycudd.DdManager_IsNsVar(self, *args)

    def SetPsVar(self, *args):
        """SetPsVar(DdManager self, int index) -> int"""
        return _pycudd.DdManager_SetPsVar(self, *args)

    def SetNsVar(self, *args):
        """SetNsVar(DdManager self, int index) -> int"""
        return _pycudd.DdManager_SetNsVar(self, *args)

    def SetPairIndex(self, *args):
        """SetPairIndex(DdManager self, int index, int pairIndex) -> int"""
        return _pycudd.DdManager_SetPairIndex(self, *args)

    def ReadPairIndex(self, *args):
        """ReadPairIndex(DdManager self, int index) -> int"""
        return _pycudd.DdManager_ReadPairIndex(self, *args)

    def SetVarToBeGrouped(self, *args):
        """SetVarToBeGrouped(DdManager self, int index) -> int"""
        return _pycudd.DdManager_SetVarToBeGrouped(self, *args)

    def SetVarHardGroup(self, *args):
        """SetVarHardGroup(DdManager self, int index) -> int"""
        return _pycudd.DdManager_SetVarHardGroup(self, *args)

    def ResetVarToBeGrouped(self, *args):
        """ResetVarToBeGrouped(DdManager self, int index) -> int"""
        return _pycudd.DdManager_ResetVarToBeGrouped(self, *args)

    def IsVarToBeGrouped(self, *args):
        """IsVarToBeGrouped(DdManager self, int index) -> int"""
        return _pycudd.DdManager_IsVarToBeGrouped(self, *args)

    def IsVarHardGroup(self, *args):
        """IsVarHardGroup(DdManager self, int index) -> int"""
        return _pycudd.DdManager_IsVarHardGroup(self, *args)

    def SetVarToBeUngrouped(self, *args):
        """SetVarToBeUngrouped(DdManager self, int index) -> int"""
        return _pycudd.DdManager_SetVarToBeUngrouped(self, *args)

    def IsVarToBeUngrouped(self, *args):
        """IsVarToBeUngrouped(DdManager self, int index) -> int"""
        return _pycudd.DdManager_IsVarToBeUngrouped(self, *args)

    def SetPiVar(self, *args):
        """SetPiVar(DdManager self, int index) -> int"""
        return _pycudd.DdManager_SetPiVar(self, *args)

    def IsPiVar(self, *args):
        """IsPiVar(DdManager self, int index) -> int"""
        return _pycudd.DdManager_IsPiVar(self, *args)

    def BindVar(self, *args):
        """BindVar(DdManager self, int index) -> int"""
        return _pycudd.DdManager_BindVar(self, *args)

    def UnbindVar(self, *args):
        """UnbindVar(DdManager self, int index) -> int"""
        return _pycudd.DdManager_UnbindVar(self, *args)

    def VarIsBound(self, *args):
        """VarIsBound(DdManager self, int index) -> int"""
        return _pycudd.DdManager_VarIsBound(self, *args)

    def ReadMaxGrowthAlternate(self):
        """ReadMaxGrowthAlternate(DdManager self) -> double"""
        return _pycudd.DdManager_ReadMaxGrowthAlternate(self)

    def SetMaxGrowthAlternate(self, *args):
        """SetMaxGrowthAlternate(DdManager self, double mg)"""
        return _pycudd.DdManager_SetMaxGrowthAlternate(self, *args)

    def ReadReorderingCycle(self):
        """ReadReorderingCycle(DdManager self) -> int"""
        return _pycudd.DdManager_ReadReorderingCycle(self)

    def SetReorderingCycle(self, *args):
        """SetReorderingCycle(DdManager self, int cycle)"""
        return _pycudd.DdManager_SetReorderingCycle(self, *args)

    def PrintCover(self, *args):
        """PrintCover(DdManager self, DdNode l, DdNode u) -> int"""
        return _pycudd.DdManager_PrintCover(self, *args)

    def Prime(self, *args):
        """Prime(DdManager self, unsigned int p) -> unsigned int"""
        return _pycudd.DdManager_Prime(self, *args)

    def __len__(self):
        """__len__(DdManager self) -> int"""
        return _pycudd.DdManager___len__(self)

    def __getitem__(self, *args):
        """__getitem__(DdManager self, int i) -> DdNode"""
        return _pycudd.DdManager___getitem__(self, *args)

    def addNewVar(self):
        """addNewVar(DdManager self) -> DdNode"""
        return _pycudd.DdManager_addNewVar(self)

    def addNewVarAtLevel(self, *args):
        """addNewVarAtLevel(DdManager self, int level) -> DdNode"""
        return _pycudd.DdManager_addNewVarAtLevel(self, *args)

    def NewVar(self):
        """NewVar(DdManager self) -> DdNode"""
        return _pycudd.DdManager_NewVar(self)

    def NewVarAtLevel(self, *args):
        """NewVarAtLevel(DdManager self, int level) -> DdNode"""
        return _pycudd.DdManager_NewVarAtLevel(self, *args)

    def addIthVar(self, *args):
        """addIthVar(DdManager self, int i) -> DdNode"""
        return _pycudd.DdManager_addIthVar(self, *args)

    def IthVar(self, *args):
        """IthVar(DdManager self, int i) -> DdNode"""
        return _pycudd.DdManager_IthVar(self, *args)

    def zddIthVar(self, *args):
        """zddIthVar(DdManager self, int i) -> DdNode"""
        return _pycudd.DdManager_zddIthVar(self, *args)

    def zddVarsFromBddVars(self, *args):
        """zddVarsFromBddVars(DdManager self, int multiplicity) -> int"""
        return _pycudd.DdManager_zddVarsFromBddVars(self, *args)

    def addConst(self, *args):
        """addConst(DdManager self, CUDD_VALUE_TYPE c) -> DdNode"""
        return _pycudd.DdManager_addConst(self, *args)

    def AutodynEnable(self, *args):
        """AutodynEnable(DdManager self, int method)"""
        return _pycudd.DdManager_AutodynEnable(self, *args)

    def AutodynDisable(self):
        """AutodynDisable(DdManager self)"""
        return _pycudd.DdManager_AutodynDisable(self)

    def ReorderingStatus(self):
        """ReorderingStatus(DdManager self) -> int"""
        return _pycudd.DdManager_ReorderingStatus(self)

    def AutodynEnableZdd(self, *args):
        """AutodynEnableZdd(DdManager self, int method)"""
        return _pycudd.DdManager_AutodynEnableZdd(self, *args)

    def AutodynDisableZdd(self):
        """AutodynDisableZdd(DdManager self)"""
        return _pycudd.DdManager_AutodynDisableZdd(self)

    def ReorderingStatusZdd(self):
        """ReorderingStatusZdd(DdManager self) -> int"""
        return _pycudd.DdManager_ReorderingStatusZdd(self)

    def zddRealignmentEnabled(self):
        """zddRealignmentEnabled(DdManager self) -> int"""
        return _pycudd.DdManager_zddRealignmentEnabled(self)

    def zddRealignEnable(self):
        """zddRealignEnable(DdManager self)"""
        return _pycudd.DdManager_zddRealignEnable(self)

    def zddRealignDisable(self):
        """zddRealignDisable(DdManager self)"""
        return _pycudd.DdManager_zddRealignDisable(self)

    def RealignmentEnabled(self):
        """RealignmentEnabled(DdManager self) -> int"""
        return _pycudd.DdManager_RealignmentEnabled(self)

    def RealignEnable(self):
        """RealignEnable(DdManager self)"""
        return _pycudd.DdManager_RealignEnable(self)

    def RealignDisable(self):
        """RealignDisable(DdManager self)"""
        return _pycudd.DdManager_RealignDisable(self)

    def ReadOne(self):
        """ReadOne(DdManager self) -> DdNode"""
        return _pycudd.DdManager_ReadOne(self)

    def ReadZddOne(self, *args):
        """ReadZddOne(DdManager self, int i) -> DdNode"""
        return _pycudd.DdManager_ReadZddOne(self, *args)

    def ReadZero(self):
        """ReadZero(DdManager self) -> DdNode"""
        return _pycudd.DdManager_ReadZero(self)

    def ReadLogicZero(self):
        """ReadLogicZero(DdManager self) -> DdNode"""
        return _pycudd.DdManager_ReadLogicZero(self)

    def ReadPlusInfinity(self):
        """ReadPlusInfinity(DdManager self) -> DdNode"""
        return _pycudd.DdManager_ReadPlusInfinity(self)

    def ReadMinusInfinity(self):
        """ReadMinusInfinity(DdManager self) -> DdNode"""
        return _pycudd.DdManager_ReadMinusInfinity(self)

    def ReadBackground(self):
        """ReadBackground(DdManager self) -> DdNode"""
        return _pycudd.DdManager_ReadBackground(self)

    def ReadCacheSlots(self):
        """ReadCacheSlots(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadCacheSlots(self)

    def ReadCacheUsedSlots(self):
        """ReadCacheUsedSlots(DdManager self) -> double"""
        return _pycudd.DdManager_ReadCacheUsedSlots(self)

    def ReadCacheLookUps(self):
        """ReadCacheLookUps(DdManager self) -> double"""
        return _pycudd.DdManager_ReadCacheLookUps(self)

    def ReadCacheHits(self):
        """ReadCacheHits(DdManager self) -> double"""
        return _pycudd.DdManager_ReadCacheHits(self)

    def ReadRecursiveCalls(self):
        """ReadRecursiveCalls(DdManager self) -> double"""
        return _pycudd.DdManager_ReadRecursiveCalls(self)

    def ReadMinHit(self):
        """ReadMinHit(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadMinHit(self)

    def SetMinHit(self, *args):
        """SetMinHit(DdManager self, unsigned int hr)"""
        return _pycudd.DdManager_SetMinHit(self, *args)

    def ReadLooseUpTo(self):
        """ReadLooseUpTo(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadLooseUpTo(self)

    def SetLooseUpTo(self, *args):
        """SetLooseUpTo(DdManager self, unsigned int lut)"""
        return _pycudd.DdManager_SetLooseUpTo(self, *args)

    def ReadMaxCache(self):
        """ReadMaxCache(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadMaxCache(self)

    def ReadMaxCacheHard(self):
        """ReadMaxCacheHard(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadMaxCacheHard(self)

    def SetMaxCacheHard(self, *args):
        """SetMaxCacheHard(DdManager self, unsigned int mc)"""
        return _pycudd.DdManager_SetMaxCacheHard(self, *args)

    def ReadSize(self):
        """ReadSize(DdManager self) -> int"""
        return _pycudd.DdManager_ReadSize(self)

    def ReadZddSize(self):
        """ReadZddSize(DdManager self) -> int"""
        return _pycudd.DdManager_ReadZddSize(self)

    def ReadSlots(self):
        """ReadSlots(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadSlots(self)

    def ReadUsedSlots(self):
        """ReadUsedSlots(DdManager self) -> double"""
        return _pycudd.DdManager_ReadUsedSlots(self)

    def ExpectedUsedSlots(self):
        """ExpectedUsedSlots(DdManager self) -> double"""
        return _pycudd.DdManager_ExpectedUsedSlots(self)

    def ReadKeys(self):
        """ReadKeys(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadKeys(self)

    def ReadDead(self):
        """ReadDead(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadDead(self)

    def ReadMinDead(self):
        """ReadMinDead(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadMinDead(self)

    def ReadReorderings(self):
        """ReadReorderings(DdManager self) -> int"""
        return _pycudd.DdManager_ReadReorderings(self)

    def ReadReorderingTime(self):
        """ReadReorderingTime(DdManager self) -> long"""
        return _pycudd.DdManager_ReadReorderingTime(self)

    def ReadGarbageCollections(self):
        """ReadGarbageCollections(DdManager self) -> int"""
        return _pycudd.DdManager_ReadGarbageCollections(self)

    def ReadGarbageCollectionTime(self):
        """ReadGarbageCollectionTime(DdManager self) -> long"""
        return _pycudd.DdManager_ReadGarbageCollectionTime(self)

    def GarbageCollect(self, *args):
        """GarbageCollect(DdManager self, int clearCache) -> int"""
        return _pycudd.DdManager_GarbageCollect(self, *args)

    def ReadNodesFreed(self):
        """ReadNodesFreed(DdManager self) -> double"""
        return _pycudd.DdManager_ReadNodesFreed(self)

    def ReadNodesDropped(self):
        """ReadNodesDropped(DdManager self) -> double"""
        return _pycudd.DdManager_ReadNodesDropped(self)

    def ReadUniqueLookUps(self):
        """ReadUniqueLookUps(DdManager self) -> double"""
        return _pycudd.DdManager_ReadUniqueLookUps(self)

    def ReadUniqueLinks(self):
        """ReadUniqueLinks(DdManager self) -> double"""
        return _pycudd.DdManager_ReadUniqueLinks(self)

    def ReadSiftMaxVar(self):
        """ReadSiftMaxVar(DdManager self) -> int"""
        return _pycudd.DdManager_ReadSiftMaxVar(self)

    def SetSiftMaxVar(self, *args):
        """SetSiftMaxVar(DdManager self, int smv)"""
        return _pycudd.DdManager_SetSiftMaxVar(self, *args)

    def ReadSiftMaxSwap(self):
        """ReadSiftMaxSwap(DdManager self) -> int"""
        return _pycudd.DdManager_ReadSiftMaxSwap(self)

    def SetSiftMaxSwap(self, *args):
        """SetSiftMaxSwap(DdManager self, int sms)"""
        return _pycudd.DdManager_SetSiftMaxSwap(self, *args)

    def ReadMaxGrowth(self):
        """ReadMaxGrowth(DdManager self) -> double"""
        return _pycudd.DdManager_ReadMaxGrowth(self)

    def SetMaxGrowth(self, *args):
        """SetMaxGrowth(DdManager self, double mg)"""
        return _pycudd.DdManager_SetMaxGrowth(self, *args)

    def ReadTree(self):
        """ReadTree(DdManager self) -> MtrNode"""
        return _pycudd.DdManager_ReadTree(self)

    def SetTree(self, *args):
        """SetTree(DdManager self, MtrNode tree)"""
        return _pycudd.DdManager_SetTree(self, *args)

    def FreeTree(self):
        """FreeTree(DdManager self)"""
        return _pycudd.DdManager_FreeTree(self)

    def ReadZddTree(self):
        """ReadZddTree(DdManager self) -> MtrNode"""
        return _pycudd.DdManager_ReadZddTree(self)

    def SetZddTree(self, *args):
        """SetZddTree(DdManager self, MtrNode tree)"""
        return _pycudd.DdManager_SetZddTree(self, *args)

    def FreeZddTree(self):
        """FreeZddTree(DdManager self)"""
        return _pycudd.DdManager_FreeZddTree(self)

    def ReadPerm(self, *args):
        """ReadPerm(DdManager self, int i) -> int"""
        return _pycudd.DdManager_ReadPerm(self, *args)

    def ReadPermZdd(self, *args):
        """ReadPermZdd(DdManager self, int i) -> int"""
        return _pycudd.DdManager_ReadPermZdd(self, *args)

    def ReadInvPerm(self, *args):
        """ReadInvPerm(DdManager self, int i) -> int"""
        return _pycudd.DdManager_ReadInvPerm(self, *args)

    def ReadInvPermZdd(self, *args):
        """ReadInvPermZdd(DdManager self, int i) -> int"""
        return _pycudd.DdManager_ReadInvPermZdd(self, *args)

    def ReadVars(self, *args):
        """ReadVars(DdManager self, int i) -> DdNode"""
        return _pycudd.DdManager_ReadVars(self, *args)

    def ReadEpsilon(self):
        """ReadEpsilon(DdManager self) -> CUDD_VALUE_TYPE"""
        return _pycudd.DdManager_ReadEpsilon(self)

    def SetEpsilon(self, *args):
        """SetEpsilon(DdManager self, CUDD_VALUE_TYPE ep)"""
        return _pycudd.DdManager_SetEpsilon(self, *args)

    def ReadGroupcheck(self):
        """ReadGroupcheck(DdManager self) -> Cudd_AggregationType"""
        return _pycudd.DdManager_ReadGroupcheck(self)

    def SetGroupcheck(self, *args):
        """SetGroupcheck(DdManager self, Cudd_AggregationType gc)"""
        return _pycudd.DdManager_SetGroupcheck(self, *args)

    def GarbageCollectionEnabled(self):
        """GarbageCollectionEnabled(DdManager self) -> int"""
        return _pycudd.DdManager_GarbageCollectionEnabled(self)

    def EnableGarbageCollection(self):
        """EnableGarbageCollection(DdManager self)"""
        return _pycudd.DdManager_EnableGarbageCollection(self)

    def DisableGarbageCollection(self):
        """DisableGarbageCollection(DdManager self)"""
        return _pycudd.DdManager_DisableGarbageCollection(self)

    def DeadAreCounted(self):
        """DeadAreCounted(DdManager self) -> int"""
        return _pycudd.DdManager_DeadAreCounted(self)

    def TurnOnCountDead(self):
        """TurnOnCountDead(DdManager self)"""
        return _pycudd.DdManager_TurnOnCountDead(self)

    def TurnOffCountDead(self):
        """TurnOffCountDead(DdManager self)"""
        return _pycudd.DdManager_TurnOffCountDead(self)

    def ReadRecomb(self):
        """ReadRecomb(DdManager self) -> int"""
        return _pycudd.DdManager_ReadRecomb(self)

    def SetRecomb(self, *args):
        """SetRecomb(DdManager self, int recomb)"""
        return _pycudd.DdManager_SetRecomb(self, *args)

    def ReadSymmviolation(self):
        """ReadSymmviolation(DdManager self) -> int"""
        return _pycudd.DdManager_ReadSymmviolation(self)

    def SetSymmviolation(self, *args):
        """SetSymmviolation(DdManager self, int symmviolation)"""
        return _pycudd.DdManager_SetSymmviolation(self, *args)

    def ReadArcviolation(self):
        """ReadArcviolation(DdManager self) -> int"""
        return _pycudd.DdManager_ReadArcviolation(self)

    def SetArcviolation(self, *args):
        """SetArcviolation(DdManager self, int arcviolation)"""
        return _pycudd.DdManager_SetArcviolation(self, *args)

    def ReadPopulationSize(self):
        """ReadPopulationSize(DdManager self) -> int"""
        return _pycudd.DdManager_ReadPopulationSize(self)

    def SetPopulationSize(self, *args):
        """SetPopulationSize(DdManager self, int populationSize)"""
        return _pycudd.DdManager_SetPopulationSize(self, *args)

    def ReadNumberXovers(self):
        """ReadNumberXovers(DdManager self) -> int"""
        return _pycudd.DdManager_ReadNumberXovers(self)

    def SetNumberXovers(self, *args):
        """SetNumberXovers(DdManager self, int numberXovers)"""
        return _pycudd.DdManager_SetNumberXovers(self, *args)

    def ReadMemoryInUse(self):
        """ReadMemoryInUse(DdManager self) -> long"""
        return _pycudd.DdManager_ReadMemoryInUse(self)

    def PrintInfo(self, *args):
        """PrintInfo(DdManager self, FILE * fp) -> int"""
        return _pycudd.DdManager_PrintInfo(self, *args)

    def ReadPeakNodeCount(self):
        """ReadPeakNodeCount(DdManager self) -> long"""
        return _pycudd.DdManager_ReadPeakNodeCount(self)

    def ReadPeakLiveNodeCount(self):
        """ReadPeakLiveNodeCount(DdManager self) -> int"""
        return _pycudd.DdManager_ReadPeakLiveNodeCount(self)

    def ReadNodeCount(self):
        """ReadNodeCount(DdManager self) -> long"""
        return _pycudd.DdManager_ReadNodeCount(self)

    def zddReadNodeCount(self):
        """zddReadNodeCount(DdManager self) -> long"""
        return _pycudd.DdManager_zddReadNodeCount(self)

    def EnableReorderingReporting(self):
        """EnableReorderingReporting(DdManager self) -> int"""
        return _pycudd.DdManager_EnableReorderingReporting(self)

    def DisableReorderingReporting(self):
        """DisableReorderingReporting(DdManager self) -> int"""
        return _pycudd.DdManager_DisableReorderingReporting(self)

    def ReorderingReporting(self):
        """ReorderingReporting(DdManager self) -> int"""
        return _pycudd.DdManager_ReorderingReporting(self)

    def ReadErrorCode(self):
        """ReadErrorCode(DdManager self) -> Cudd_ErrorType"""
        return _pycudd.DdManager_ReadErrorCode(self)

    def ClearErrorCode(self):
        """ClearErrorCode(DdManager self)"""
        return _pycudd.DdManager_ClearErrorCode(self)

    def ReadStdout(self):
        """ReadStdout(DdManager self) -> FILE *"""
        return _pycudd.DdManager_ReadStdout(self)

    def SetStdout(self, *args):
        """SetStdout(DdManager self, FILE * fp)"""
        return _pycudd.DdManager_SetStdout(self, *args)

    def ReadStderr(self):
        """ReadStderr(DdManager self) -> FILE *"""
        return _pycudd.DdManager_ReadStderr(self)

    def SetStderr(self, *args):
        """SetStderr(DdManager self, FILE * fp)"""
        return _pycudd.DdManager_SetStderr(self, *args)

    def ReadNextReordering(self):
        """ReadNextReordering(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadNextReordering(self)

    def ReadSwapSteps(self):
        """ReadSwapSteps(DdManager self) -> double"""
        return _pycudd.DdManager_ReadSwapSteps(self)

    def ReadMaxLive(self):
        """ReadMaxLive(DdManager self) -> unsigned int"""
        return _pycudd.DdManager_ReadMaxLive(self)

    def SetMaxLive(self, *args):
        """SetMaxLive(DdManager self, unsigned int maxLive)"""
        return _pycudd.DdManager_SetMaxLive(self, *args)

    def ReadMaxMemory(self):
        """ReadMaxMemory(DdManager self) -> long"""
        return _pycudd.DdManager_ReadMaxMemory(self)

    def SetMaxMemory(self, *args):
        """SetMaxMemory(DdManager self, long maxMemory)"""
        return _pycudd.DdManager_SetMaxMemory(self, *args)

    def SetNextReordering(self, *args):
        """SetNextReordering(DdManager self, unsigned int next)"""
        return _pycudd.DdManager_SetNextReordering(self, *args)

    def DebugCheck(self):
        """DebugCheck(DdManager self) -> int"""
        return _pycudd.DdManager_DebugCheck(self)

    def CheckKeys(self):
        """CheckKeys(DdManager self) -> int"""
        return _pycudd.DdManager_CheckKeys(self)

    def MakeTreeNode(self, *args):
        """MakeTreeNode(DdManager self, unsigned int low, unsigned int size, unsigned int type) -> MtrNode"""
        return _pycudd.DdManager_MakeTreeNode(self, *args)

    def PrintLinear(self):
        """PrintLinear(DdManager self) -> int"""
        return _pycudd.DdManager_PrintLinear(self)

    def ReadLinear(self, *args):
        """ReadLinear(DdManager self, int x, int y) -> int"""
        return _pycudd.DdManager_ReadLinear(self, *args)

    def CheckZeroRef(self):
        """CheckZeroRef(DdManager self) -> int"""
        return _pycudd.DdManager_CheckZeroRef(self)

    def ReduceHeap(self, *args):
        """ReduceHeap(DdManager self, int heuristic, int minsize) -> int"""
        return _pycudd.DdManager_ReduceHeap(self, *args)

    def ShuffleHeap(self, *args):
        """ShuffleHeap(DdManager self, IntArray permutation) -> int"""
        return _pycudd.DdManager_ShuffleHeap(self, *args)

    def SymmProfile(self, *args):
        """SymmProfile(DdManager self, int lower, int upper)"""
        return _pycudd.DdManager_SymmProfile(self, *args)

    def IndicesToCube(self, *args):
        """IndicesToCube(DdManager self, IntArray array, int n) -> DdNode"""
        return _pycudd.DdManager_IndicesToCube(self, *args)

    def AverageDistance(self):
        """AverageDistance(DdManager self) -> double"""
        return _pycudd.DdManager_AverageDistance(self)

    def MakeZddTreeNode(self, *args):
        """MakeZddTreeNode(DdManager self, unsigned int low, unsigned int size, unsigned int type) -> MtrNode"""
        return _pycudd.DdManager_MakeZddTreeNode(self, *args)

    def zddPrintSubtable(self):
        """zddPrintSubtable(DdManager self)"""
        return _pycudd.DdManager_zddPrintSubtable(self)

    def zddReduceHeap(self, *args):
        """zddReduceHeap(DdManager self, int heuristic, int minsize) -> int"""
        return _pycudd.DdManager_zddReduceHeap(self, *args)

    def zddShuffleHeap(self, *args):
        """zddShuffleHeap(DdManager self, IntArray permutation) -> int"""
        return _pycudd.DdManager_zddShuffleHeap(self, *args)

    def zddSymmProfile(self, *args):
        """zddSymmProfile(DdManager self, int lower, int upper)"""
        return _pycudd.DdManager_zddSymmProfile(self, *args)

    def BddToAdd(self, *args):
        """BddToAdd(DdManager self, DdNode B) -> DdNode"""
        return _pycudd.DdManager_BddToAdd(self, *args)

    def addBddPattern(self, *args):
        """addBddPattern(DdManager self, DdNode f) -> DdNode"""
        return _pycudd.DdManager_addBddPattern(self, *args)

    def addBddThreshold(self, *args):
        """addBddThreshold(DdManager self, DdNode f, CUDD_VALUE_TYPE value) -> DdNode"""
        return _pycudd.DdManager_addBddThreshold(self, *args)

    def addBddStrictThreshold(self, *args):
        """addBddStrictThreshold(DdManager self, DdNode f, CUDD_VALUE_TYPE value) -> DdNode"""
        return _pycudd.DdManager_addBddStrictThreshold(self, *args)

    def addBddInterval(self, *args):
        """addBddInterval(DdManager self, DdNode f, CUDD_VALUE_TYPE lower, CUDD_VALUE_TYPE upper) -> DdNode"""
        return _pycudd.DdManager_addBddInterval(self, *args)

    def addBddIthBit(self, *args):
        """addBddIthBit(DdManager self, DdNode f, int bit) -> DdNode"""
        return _pycudd.DdManager_addBddIthBit(self, *args)

    def zddPortFromBdd(self, *args):
        """zddPortFromBdd(DdManager self, DdNode B) -> DdNode"""
        return _pycudd.DdManager_zddPortFromBdd(self, *args)

    def zddPortToBdd(self, *args):
        """zddPortToBdd(DdManager self, DdNode f) -> DdNode"""
        return _pycudd.DdManager_zddPortToBdd(self, *args)

    def MakeBddFromZddCover(self, *args):
        """MakeBddFromZddCover(DdManager self, DdNode node) -> DdNode"""
        return _pycudd.DdManager_MakeBddFromZddCover(self, *args)

    def PrintVersion(self, *args):
        """PrintVersion(DdManager self, FILE * fp)"""
        return _pycudd.DdManager_PrintVersion(self, *args)

    def Random(self):
        """Random(DdManager self) -> long"""
        return _pycudd.DdManager_Random(self)

    def Srandom(self, *args):
        """Srandom(DdManager self, long seed)"""
        return _pycudd.DdManager_Srandom(self, *args)

    def OutOfMem(self, *args):
        """OutOfMem(DdManager self, long size)"""
        return _pycudd.DdManager_OutOfMem(self, *args)

    def Transfer(self, *args):
        """Transfer(DdManager self, DdManager ddDestination, DdNode f) -> DdNode"""
        return _pycudd.DdManager_Transfer(self, *args)

    def CubeArrayToBdd(self, *args):
        """CubeArrayToBdd(DdManager self, IntArray y) -> DdNode"""
        return _pycudd.DdManager_CubeArrayToBdd(self, *args)

    def SetVarMap(self, *args):
        """SetVarMap(DdManager self, DdArray x, DdArray y, int n) -> int"""
        return _pycudd.DdManager_SetVarMap(self, *args)

    def ComputeCube(self, *args):
        """ComputeCube(DdManager self, DdArray vars, IntArray phase, int n) -> DdNode"""
        return _pycudd.DdManager_ComputeCube(self, *args)

    def zddDumpDot(self, *args):
        """zddDumpDot(DdManager self, int n, DdArray f, char ** inames, char ** onames, FILE * fp) -> int"""
        return _pycudd.DdManager_zddDumpDot(self, *args)

    def DumpBlif(self, *args):
        """DumpBlif(DdManager self, int n, DdArray f, char ** inames, char ** onames, char * mname, FILE * fp, int mv) -> int"""
        return _pycudd.DdManager_DumpBlif(self, *args)

    def DumpBlifBody(self, *args):
        """DumpBlifBody(DdManager self, int n, DdArray f, char ** inames, char ** onames, FILE * fp, int mv) -> int"""
        return _pycudd.DdManager_DumpBlifBody(self, *args)

    def DumpDot(self, *args):
        """DumpDot(DdManager self, int n, DdArray f, char ** inames, char ** onames, FILE * fp) -> int"""
        return _pycudd.DdManager_DumpDot(self, *args)

    def DumpDaVinci(self, *args):
        """DumpDaVinci(DdManager self, int n, DdArray f, char ** inames, char ** onames, FILE * fp) -> int"""
        return _pycudd.DdManager_DumpDaVinci(self, *args)

    def DumpDDcal(self, *args):
        """DumpDDcal(DdManager self, int n, DdArray f, char ** inames, char ** onames, FILE * fp) -> int"""
        return _pycudd.DdManager_DumpDDcal(self, *args)

    def DumpFactoredForm(self, *args):
        """DumpFactoredForm(DdManager self, int n, DdArray f, char ** inames, char ** onames, FILE * fp) -> int"""
        return _pycudd.DdManager_DumpFactoredForm(self, *args)

    def ArrayLoad(self, *args):
        """
        ArrayLoad(DdManager self, int rootmatchmode, char ** rootmatchnames, int varmatchmode, char ** varmatchnames, 
            IntArray varmatchauxids, IntArray varcomposeids, int mode, char * filename, 
            FILE * fp, DdArray pproots) -> int
        """
        return _pycudd.DdManager_ArrayLoad(self, *args)

    def ArrayStore(self, *args):
        """
        ArrayStore(DdManager self, char * ddname, DdArray roots, char ** rootnames, char ** varnames, IntArray auxids, 
            int mode, int varinfo, char * filename, FILE * fp) -> int
        """
        return _pycudd.DdManager_ArrayStore(self, *args)

    def BddLoad(self, *args):
        """
        BddLoad(DdManager self, int varmatchmode, char ** varmatchnames, IntArray varmatchauxids, IntArray varcomposeids, 
            int mode, char * filename, FILE * fp) -> DdNode
        """
        return _pycudd.DdManager_BddLoad(self, *args)

    def BddStore(self, *args):
        """
        BddStore(DdManager self, char * ddname, DdNode f, char ** varnames, IntArray auxids, int mode, int varinfo, 
            char * fname, FILE * fp) -> int
        """
        return _pycudd.DdManager_BddStore(self, *args)

    def Bin2Text(self, *args):
        """Bin2Text(DdManager self, char * filein, char * fileout) -> int"""
        return _pycudd.DdManager_Bin2Text(self, *args)

    def DisplayBinary(self, *args):
        """DisplayBinary(DdManager self, char * filein, char * fileout) -> int"""
        return _pycudd.DdManager_DisplayBinary(self, *args)

    def Text2Bin(self, *args):
        """Text2Bin(DdManager self, char * filein, char * fileout) -> int"""
        return _pycudd.DdManager_Text2Bin(self, *args)

    def VectorSupportSize(self, *args):
        """VectorSupportSize(DdManager self, DdArray F, int n) -> int"""
        return _pycudd.DdManager_VectorSupportSize(self, *args)

    def ClassifySupport(self, *args):
        """ClassifySupport(DdManager self, DdNode f, DdNode g, DdArray common, DdArray onlyF, DdArray onlyG) -> int"""
        return _pycudd.DdManager_ClassifySupport(self, *args)

    def Xgty(self, *args):
        """Xgty(DdManager self, int N, DdArray z, DdArray x, DdArray y) -> DdNode"""
        return _pycudd.DdManager_Xgty(self, *args)

    def Xeqy(self, *args):
        """Xeqy(DdManager self, int N, DdArray x, DdArray y) -> DdNode"""
        return _pycudd.DdManager_Xeqy(self, *args)

    def Dxygtdxz(self, *args):
        """Dxygtdxz(DdManager self, int N, DdArray x, DdArray y, DdArray z) -> DdNode"""
        return _pycudd.DdManager_Dxygtdxz(self, *args)

    def Dxygtdyz(self, *args):
        """Dxygtdyz(DdManager self, int N, DdArray x, DdArray y, DdArray z) -> DdNode"""
        return _pycudd.DdManager_Dxygtdyz(self, *args)

    def SharingSize(self, *args):
        """SharingSize(DdManager self, DdArray nodeArray, int n) -> int"""
        return _pycudd.DdManager_SharingSize(self, *args)

    def ReadIndex(self, *args):
        """ReadIndex(DdManager self, int i) -> int"""
        return _pycudd.DdManager_ReadIndex(self, *args)

    def addPlus(self, *args):
        """addPlus(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addPlus(self, *args)

    def addTimes(self, *args):
        """addTimes(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addTimes(self, *args)

    def addThreshold(self, *args):
        """addThreshold(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addThreshold(self, *args)

    def addSetNZ(self, *args):
        """addSetNZ(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addSetNZ(self, *args)

    def addDivide(self, *args):
        """addDivide(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addDivide(self, *args)

    def addMinus(self, *args):
        """addMinus(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addMinus(self, *args)

    def addMinimum(self, *args):
        """addMinimum(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addMinimum(self, *args)

    def addMaximum(self, *args):
        """addMaximum(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addMaximum(self, *args)

    def addOneZeroMaximum(self, *args):
        """addOneZeroMaximum(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addOneZeroMaximum(self, *args)

    def addDiff(self, *args):
        """addDiff(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addDiff(self, *args)

    def addAgreement(self, *args):
        """addAgreement(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addAgreement(self, *args)

    def addOr(self, *args):
        """addOr(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addOr(self, *args)

    def addNand(self, *args):
        """addNand(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addNand(self, *args)

    def addNor(self, *args):
        """addNor(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addNor(self, *args)

    def addXor(self, *args):
        """addXor(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addXor(self, *args)

    def addXnor(self, *args):
        """addXnor(DdManager self, DdArray f, DdArray g) -> DdNode"""
        return _pycudd.DdManager_addXnor(self, *args)

    def addWalsh(self, *args):
        """addWalsh(DdManager self, DdArray x, DdArray y, int n) -> DdNode"""
        return _pycudd.DdManager_addWalsh(self, *args)

    def addHamming(self, *args):
        """addHamming(DdManager self, DdArray xVars, DdArray yVars, int nVars) -> DdNode"""
        return _pycudd.DdManager_addHamming(self, *args)

    def addComputeCube(self, *args):
        """addComputeCube(DdManager self, DdArray vars, IntArray phase, int n) -> DdNode"""
        return _pycudd.DdManager_addComputeCube(self, *args)

    def addResidue(self, *args):
        """addResidue(DdManager self, int n, int m, int options, int top) -> DdNode"""
        return _pycudd.DdManager_addResidue(self, *args)

    def addXeqy(self, *args):
        """addXeqy(DdManager self, int N, DdArray x, DdArray y) -> DdNode"""
        return _pycudd.DdManager_addXeqy(self, *args)

    def ApaNumberOfDigits(self, *args):
        """ApaNumberOfDigits(DdManager self, int binaryDigits) -> int"""
        return _pycudd.DdManager_ApaNumberOfDigits(self, *args)

    def NewApaNumber(self, *args):
        """NewApaNumber(DdManager self, int digits) -> DdApaNumber"""
        return _pycudd.DdManager_NewApaNumber(self, *args)

    def ApaCopy(self, *args):
        """ApaCopy(DdManager self, int digits, DdApaNumber source, DdApaNumber dest)"""
        return _pycudd.DdManager_ApaCopy(self, *args)

    def ApaAdd(self, *args):
        """ApaAdd(DdManager self, int digits, DdApaNumber a, DdApaNumber b, DdApaNumber sum) -> DdApaDigit"""
        return _pycudd.DdManager_ApaAdd(self, *args)

    def ApaSubtract(self, *args):
        """ApaSubtract(DdManager self, int digits, DdApaNumber a, DdApaNumber b, DdApaNumber diff) -> DdApaDigit"""
        return _pycudd.DdManager_ApaSubtract(self, *args)

    def ApaShortDivision(self, *args):
        """ApaShortDivision(DdManager self, int digits, DdApaNumber dividend, DdApaDigit divisor, DdApaNumber quotient) -> DdApaDigit"""
        return _pycudd.DdManager_ApaShortDivision(self, *args)

    def ApaIntDivision(self, *args):
        """ApaIntDivision(DdManager self, int digits, DdApaNumber dividend, unsigned int divisor, DdApaNumber quotient) -> unsigned int"""
        return _pycudd.DdManager_ApaIntDivision(self, *args)

    def ApaShiftRight(self, *args):
        """ApaShiftRight(DdManager self, int digits, DdApaDigit _in, DdApaNumber a, DdApaNumber b)"""
        return _pycudd.DdManager_ApaShiftRight(self, *args)

    def ApaSetToLiteral(self, *args):
        """ApaSetToLiteral(DdManager self, int digits, DdApaNumber number, DdApaDigit literal)"""
        return _pycudd.DdManager_ApaSetToLiteral(self, *args)

    def ApaPowerOfTwo(self, *args):
        """ApaPowerOfTwo(DdManager self, int digits, DdApaNumber number, int power)"""
        return _pycudd.DdManager_ApaPowerOfTwo(self, *args)

    def ApaCompare(self, *args):
        """ApaCompare(DdManager self, int digitsFirst, DdApaNumber first, int digitsSecond, DdApaNumber second) -> int"""
        return _pycudd.DdManager_ApaCompare(self, *args)

    def ApaCompareRatios(self, *args):
        """
        ApaCompareRatios(DdManager self, int digitsFirst, DdApaNumber firstNum, unsigned int firstDen, int digitsSecond, DdApaNumber secondNum, 
            unsigned int secondDen) -> int
        """
        return _pycudd.DdManager_ApaCompareRatios(self, *args)

    def ApaPrintHex(self, *args):
        """ApaPrintHex(DdManager self, FILE * fp, int digits, DdApaNumber number) -> int"""
        return _pycudd.DdManager_ApaPrintHex(self, *args)

    def ApaPrintDecimal(self, *args):
        """ApaPrintDecimal(DdManager self, FILE * fp, int digits, DdApaNumber number) -> int"""
        return _pycudd.DdManager_ApaPrintDecimal(self, *args)

    def ApaPrintExponential(self, *args):
        """ApaPrintExponential(DdManager self, FILE * fp, int digits, DdApaNumber number, int precision) -> int"""
        return _pycudd.DdManager_ApaPrintExponential(self, *args)

    def One(self):
        """One(DdManager self) -> DdNode"""
        return _pycudd.DdManager_One(self)

    def Zero(self):
        """Zero(DdManager self) -> DdNode"""
        return _pycudd.DdManager_Zero(self)

    def Sort(self, *args):
        """Sort(DdManager self, DdNode leftnd, DdNode rightnd) -> int"""
        return _pycudd.DdManager_Sort(self, *args)

    def PrintStdOut(self):
        """PrintStdOut(DdManager self) -> int"""
        return _pycudd.DdManager_PrintStdOut(self)

    def StateCube(self, *args):
        """StateCube(DdManager self, char * cube, int base, int offset, int scale) -> DdNode"""
        return _pycudd.DdManager_StateCube(self, *args)

    def SetDefault(self):
        """SetDefault(DdManager self)"""
        return _pycudd.DdManager_SetDefault(self)

DdManager_swigregister = _pycudd.DdManager_swigregister
DdManager_swigregister(DdManager)

class DdGen(_object):
    """Proxy of C++ DdGen class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, DdGen, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DdGen, name)
    __repr__ = _swig_repr
    __doc__ = "Not expected to be used directly."

    def __init__(self, *args): 
        """
        __init__(DdGen self, DdNode node1, int method, DdNode node2=None) -> DdGen
        __init__(DdGen self, DdNode node1, int method) -> DdGen
        """
        this = _pycudd.new_DdGen(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_DdGen
    __del__ = lambda self : None;
DdGen_swigregister = _pycudd.DdGen_swigregister
DdGen_swigregister(DdGen)

class DdNode(_object):
    """Proxy of C++ DdNode class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, DdNode, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DdNode, name)
    __repr__ = _swig_repr
    def __iter__(self):
      global iter_meth, cudd_version
      if iter_meth == 0:
        return ForeachCubeIterator(self)
      elif iter_meth == 1:
        return ForeachNodeIterator(self)
      elif iter_meth == 2:
        if cudd_version < 0x020400:
          print "Cannot iterate over primes with CUDD < 2.4.0"
          raise RuntimeError
        npair = NodePair(self,self)
        return ForeachPrimeIterator(npair)
    def __deepcopy__(self,memo):
      return self
    __doc__ = "This class wraps around the basic DdNode. The methods defined by this class take the default manager as their DdManager option (if needed) and provide themselves as the first DdNode option that those functions require, as indicated by the self argument. These functions may be found in ddnode.i."

    def __init__(self): 
        """__init__(DdNode self) -> DdNode"""
        this = _pycudd.new_DdNode()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_DdNode
    __del__ = lambda self : None;
    def FirstCube(self, *args):
        """FirstCube(DdNode self, DdGen gen) -> int"""
        return _pycudd.DdNode_FirstCube(self, *args)

    def NextCube(self, *args):
        """NextCube(DdNode self, DdGen gen) -> int"""
        return _pycudd.DdNode_NextCube(self, *args)

    def FirstNode(self, *args):
        """FirstNode(DdNode self, DdGen gen) -> int"""
        return _pycudd.DdNode_FirstNode(self, *args)

    def NextNode(self, *args):
        """NextNode(DdNode self, DdGen gen) -> int"""
        return _pycudd.DdNode_NextNode(self, *args)

    def AndAbstractLimit(self, *args):
        """AndAbstractLimit(DdNode self, DdNode g, DdNode cube, unsigned int limit) -> DdNode"""
        return _pycudd.DdNode_AndAbstractLimit(self, *args)

    def AndLimit(self, *args):
        """AndLimit(DdNode self, DdNode g, unsigned int limit) -> DdNode"""
        return _pycudd.DdNode_AndLimit(self, *args)

    def NPAnd(self, *args):
        """NPAnd(DdNode self, DdNode c) -> DdNode"""
        return _pycudd.DdNode_NPAnd(self, *args)

    def FindTwoLiteralClauses(self):
        """FindTwoLiteralClauses(DdNode self) -> DdTlcInfo"""
        return _pycudd.DdNode_FindTwoLiteralClauses(self)

    def EpdCountMinterm(self, *args):
        """EpdCountMinterm(DdNode self, int nvars, EpDouble epd) -> int"""
        return _pycudd.DdNode_EpdCountMinterm(self, *args)

    def ApproxConjDecomp(self):
        """ApproxConjDecomp(DdNode self) -> int"""
        return _pycudd.DdNode_ApproxConjDecomp(self)

    def ApproxDisjDecomp(self):
        """ApproxDisjDecomp(DdNode self) -> int"""
        return _pycudd.DdNode_ApproxDisjDecomp(self)

    def IterConjDecomp(self):
        """IterConjDecomp(DdNode self) -> int"""
        return _pycudd.DdNode_IterConjDecomp(self)

    def IterDisjDecomp(self):
        """IterDisjDecomp(DdNode self) -> int"""
        return _pycudd.DdNode_IterDisjDecomp(self)

    def GenConjDecomp(self):
        """GenConjDecomp(DdNode self) -> int"""
        return _pycudd.DdNode_GenConjDecomp(self)

    def GenDisjDecomp(self):
        """GenDisjDecomp(DdNode self) -> int"""
        return _pycudd.DdNode_GenDisjDecomp(self)

    def VarConjDecomp(self):
        """VarConjDecomp(DdNode self) -> int"""
        return _pycudd.DdNode_VarConjDecomp(self)

    def VarDisjDecomp(self):
        """VarDisjDecomp(DdNode self) -> int"""
        return _pycudd.DdNode_VarDisjDecomp(self)

    def ClosestCube(self, *args):
        """ClosestCube(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_ClosestCube(self, *args)

    def LeqUnless(self, *args):
        """LeqUnless(DdNode self, DdNode g, DdNode D) -> int"""
        return _pycudd.DdNode_LeqUnless(self, *args)

    def MakePrime(self, *args):
        """MakePrime(DdNode self, DdNode f) -> DdNode"""
        return _pycudd.DdNode_MakePrime(self, *args)

    def CountPathsToNonZero(self):
        """CountPathsToNonZero(DdNode self) -> double"""
        return _pycudd.DdNode_CountPathsToNonZero(self)

    def SupportIndex(self):
        """SupportIndex(DdNode self) -> int"""
        return _pycudd.DdNode_SupportIndex(self)

    def ExistAbstract(self, *args):
        """ExistAbstract(DdNode self, DdNode cube) -> DdNode"""
        return _pycudd.DdNode_ExistAbstract(self, *args)

    def XorExistAbstract(self, *args):
        """XorExistAbstract(DdNode self, DdNode g, DdNode cube) -> DdNode"""
        return _pycudd.DdNode_XorExistAbstract(self, *args)

    def UnivAbstract(self, *args):
        """UnivAbstract(DdNode self, DdNode cube) -> DdNode"""
        return _pycudd.DdNode_UnivAbstract(self, *args)

    def BooleanDiff(self, *args):
        """BooleanDiff(DdNode self, int x) -> DdNode"""
        return _pycudd.DdNode_BooleanDiff(self, *args)

    def AndAbstract(self, *args):
        """AndAbstract(DdNode self, DdNode g, DdNode cube) -> DdNode"""
        return _pycudd.DdNode_AndAbstract(self, *args)

    def VarIsDependent(self, *args):
        """VarIsDependent(DdNode self, DdNode var) -> int"""
        return _pycudd.DdNode_VarIsDependent(self, *args)

    def Correlation(self, *args):
        """Correlation(DdNode self, DdNode g) -> double"""
        return _pycudd.DdNode_Correlation(self, *args)

    def CorrelationWeights(self, *args):
        """CorrelationWeights(DdNode self, DdNode g, DoubleArray prob) -> double"""
        return _pycudd.DdNode_CorrelationWeights(self, *args)

    def Ite(self, *args):
        """Ite(DdNode self, DdNode g, DdNode h) -> DdNode"""
        return _pycudd.DdNode_Ite(self, *args)

    def IteConstant(self, *args):
        """IteConstant(DdNode self, DdNode g, DdNode h) -> DdNode"""
        return _pycudd.DdNode_IteConstant(self, *args)

    def Intersect(self, *args):
        """Intersect(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_Intersect(self, *args)

    def FIntersect(self, *args):
        """FIntersect(DdNode self, DdNode g) -> int"""
        return _pycudd.DdNode_FIntersect(self, *args)

    def And(self, *args):
        """And(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_And(self, *args)

    def Or(self, *args):
        """Or(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_Or(self, *args)

    def Nand(self, *args):
        """Nand(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_Nand(self, *args)

    def Nor(self, *args):
        """Nor(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_Nor(self, *args)

    def Xor(self, *args):
        """Xor(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_Xor(self, *args)

    def Xnor(self, *args):
        """Xnor(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_Xnor(self, *args)

    def ClippingAnd(self, *args):
        """ClippingAnd(DdNode self, DdNode g, int maxDepth, int direction) -> DdNode"""
        return _pycudd.DdNode_ClippingAnd(self, *args)

    def ClippingAndAbstract(self, *args):
        """ClippingAndAbstract(DdNode self, DdNode g, DdNode cube, int maxDepth, int direction) -> DdNode"""
        return _pycudd.DdNode_ClippingAndAbstract(self, *args)

    def LICompaction(self, *args):
        """LICompaction(DdNode self, DdNode c) -> DdNode"""
        return _pycudd.DdNode_LICompaction(self, *args)

    def Squeeze(self, *args):
        """Squeeze(DdNode self, DdNode u) -> DdNode"""
        return _pycudd.DdNode_Squeeze(self, *args)

    def Minimize(self, *args):
        """Minimize(DdNode self, DdNode c) -> DdNode"""
        return _pycudd.DdNode_Minimize(self, *args)

    def Constrain(self, *args):
        """Constrain(DdNode self, DdNode c) -> DdNode"""
        return _pycudd.DdNode_Constrain(self, *args)

    def Restrict(self, *args):
        """Restrict(DdNode self, DdNode c) -> DdNode"""
        return _pycudd.DdNode_Restrict(self, *args)

    def PickOneCube(self, *args):
        """PickOneCube(DdNode self, char * string) -> int"""
        return _pycudd.DdNode_PickOneCube(self, *args)

    def PickOneMinterm(self, *args):
        """PickOneMinterm(DdNode self, DdArray vars, int n) -> DdNode"""
        return _pycudd.DdNode_PickOneMinterm(self, *args)

    def PickArbitraryMinterms(self, *args):
        """PickArbitraryMinterms(DdNode self, DdArray vars, int n, int k) -> DdArray"""
        return _pycudd.DdNode_PickArbitraryMinterms(self, *args)

    def Compose(self, *args):
        """Compose(DdNode self, DdNode g, int v) -> DdNode"""
        return _pycudd.DdNode_Compose(self, *args)

    def Permute(self, *args):
        """Permute(DdNode self, IntArray permut) -> DdNode"""
        return _pycudd.DdNode_Permute(self, *args)

    def VarMap(self):
        """VarMap(DdNode self) -> DdNode"""
        return _pycudd.DdNode_VarMap(self)

    def LiteralSetIntersection(self, *args):
        """LiteralSetIntersection(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_LiteralSetIntersection(self, *args)

    def IsVarEssential(self, *args):
        """IsVarEssential(DdNode self, int id, int phase) -> int"""
        return _pycudd.DdNode_IsVarEssential(self, *args)

    def Leq(self, *args):
        """Leq(DdNode self, DdNode g) -> bool"""
        return _pycudd.DdNode_Leq(self, *args)

    def CharToVect(self):
        """CharToVect(DdNode self) -> DdArray"""
        return _pycudd.DdNode_CharToVect(self)

    def ConstrainDecomp(self):
        """ConstrainDecomp(DdNode self) -> DdArray"""
        return _pycudd.DdNode_ConstrainDecomp(self)

    def Isop(self, *args):
        """Isop(DdNode self, DdNode U) -> DdNode"""
        return _pycudd.DdNode_Isop(self, *args)

    def SwapVariables(self, *args):
        """SwapVariables(DdNode self, DdArray x, DdArray y, int n) -> DdNode"""
        return _pycudd.DdNode_SwapVariables(self, *args)

    def AdjPermuteX(self, *args):
        """AdjPermuteX(DdNode self, DdArray x, int n) -> DdNode"""
        return _pycudd.DdNode_AdjPermuteX(self, *args)

    def VectorCompose(self, *args):
        """VectorCompose(DdNode self, DdArray vector) -> DdNode"""
        return _pycudd.DdNode_VectorCompose(self, *args)

    def SetBackground(self):
        """SetBackground(DdNode self)"""
        return _pycudd.DdNode_SetBackground(self)

    def UnderApprox(self, *args):
        """UnderApprox(DdNode self, int numVars, int threshold, int safe, double quality) -> DdNode"""
        return _pycudd.DdNode_UnderApprox(self, *args)

    def OverApprox(self, *args):
        """OverApprox(DdNode self, int numVars, int threshold, int safe, double quality) -> DdNode"""
        return _pycudd.DdNode_OverApprox(self, *args)

    def RemapUnderApprox(self, *args):
        """RemapUnderApprox(DdNode self, int numVars, int threshold, double quality) -> DdNode"""
        return _pycudd.DdNode_RemapUnderApprox(self, *args)

    def RemapOverApprox(self, *args):
        """RemapOverApprox(DdNode self, int numVars, int threshold, double quality) -> DdNode"""
        return _pycudd.DdNode_RemapOverApprox(self, *args)

    def BiasedUnderApprox(self, *args):
        """BiasedUnderApprox(DdNode self, DdNode b, int numVars, int threshold, double quality1, double quality0) -> DdNode"""
        return _pycudd.DdNode_BiasedUnderApprox(self, *args)

    def BiasedOverApprox(self, *args):
        """BiasedOverApprox(DdNode self, DdNode b, int numVars, int threshold, double quality1, double quality0) -> DdNode"""
        return _pycudd.DdNode_BiasedOverApprox(self, *args)

    def Cofactor(self, *args):
        """Cofactor(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_Cofactor(self, *args)

    def FindEssential(self):
        """FindEssential(DdNode self) -> DdNode"""
        return _pycudd.DdNode_FindEssential(self)

    def SubsetCompress(self, *args):
        """SubsetCompress(DdNode self, int nvars, int threshold) -> DdNode"""
        return _pycudd.DdNode_SubsetCompress(self, *args)

    def SupersetCompress(self, *args):
        """SupersetCompress(DdNode self, int nvars, int threshold) -> DdNode"""
        return _pycudd.DdNode_SupersetCompress(self, *args)

    def CProjection(self, *args):
        """CProjection(DdNode self, DdNode Y) -> DdNode"""
        return _pycudd.DdNode_CProjection(self, *args)

    def MinHammingDist(self, *args):
        """MinHammingDist(DdNode self, IntArray minterm, int upperBound) -> int"""
        return _pycudd.DdNode_MinHammingDist(self, *args)

    def Eval(self, *args):
        """Eval(DdNode self, IntArray inputs) -> DdNode"""
        return _pycudd.DdNode_Eval(self, *args)

    def ShortestPath(self, *args):
        """ShortestPath(DdNode self, IntArray weight, IntArray support, IntArray length) -> DdNode"""
        return _pycudd.DdNode_ShortestPath(self, *args)

    def LargestCube(self, *args):
        """LargestCube(DdNode self, IntArray length) -> DdNode"""
        return _pycudd.DdNode_LargestCube(self, *args)

    def ShortestLength(self, *args):
        """ShortestLength(DdNode self, IntArray weight) -> int"""
        return _pycudd.DdNode_ShortestLength(self, *args)

    def Decreasing(self, *args):
        """Decreasing(DdNode self, int i) -> DdNode"""
        return _pycudd.DdNode_Decreasing(self, *args)

    def Increasing(self, *args):
        """Increasing(DdNode self, int i) -> DdNode"""
        return _pycudd.DdNode_Increasing(self, *args)

    def EquivDC(self, *args):
        """EquivDC(DdNode self, DdNode G, DdNode D) -> int"""
        return _pycudd.DdNode_EquivDC(self, *args)

    def EqualSupNorm(self, *args):
        """EqualSupNorm(DdNode self, DdNode g, CUDD_VALUE_TYPE tolerance, int pr) -> int"""
        return _pycudd.DdNode_EqualSupNorm(self, *args)

    def CofMinterm(self):
        """CofMinterm(DdNode self) -> DoubleArray"""
        return _pycudd.DdNode_CofMinterm(self)

    def VerifySol(self, *args):
        """VerifySol(DdNode self, DdArray G, IntArray yIndex, int n) -> DdNode"""
        return _pycudd.DdNode_VerifySol(self, *args)

    def SplitSet(self, *args):
        """SplitSet(DdNode self, DdArray xVars, int n, double m) -> DdNode"""
        return _pycudd.DdNode_SplitSet(self, *args)

    def SubsetHeavyBranch(self, *args):
        """SubsetHeavyBranch(DdNode self, int numVars, int threshold) -> DdNode"""
        return _pycudd.DdNode_SubsetHeavyBranch(self, *args)

    def SupersetHeavyBranch(self, *args):
        """SupersetHeavyBranch(DdNode self, int numVars, int threshold) -> DdNode"""
        return _pycudd.DdNode_SupersetHeavyBranch(self, *args)

    def SubsetShortPaths(self, *args):
        """SubsetShortPaths(DdNode self, int numVars, int threshold, int hardlimit) -> DdNode"""
        return _pycudd.DdNode_SubsetShortPaths(self, *args)

    def SupersetShortPaths(self, *args):
        """SupersetShortPaths(DdNode self, int numVars, int threshold, int hardlimit) -> DdNode"""
        return _pycudd.DdNode_SupersetShortPaths(self, *args)

    def BddToCubeArray(self, *args):
        """BddToCubeArray(DdNode self, IntArray y) -> int"""
        return _pycudd.DdNode_BddToCubeArray(self, *args)

    def PrintMinterm(self):
        """PrintMinterm(DdNode self) -> int"""
        return _pycudd.DdNode_PrintMinterm(self)

    def PrintDebug(self, *args):
        """PrintDebug(DdNode self, int n, int pr) -> int"""
        return _pycudd.DdNode_PrintDebug(self, *args)

    def EstimateCofactor(self, *args):
        """EstimateCofactor(DdNode self, int i, int phase) -> int"""
        return _pycudd.DdNode_EstimateCofactor(self, *args)

    def CountMinterm(self, *args):
        """CountMinterm(DdNode self, int nvars) -> double"""
        return _pycudd.DdNode_CountMinterm(self, *args)

    def Support(self):
        """Support(DdNode self) -> DdNode"""
        return _pycudd.DdNode_Support(self)

    def SupportSize(self):
        """SupportSize(DdNode self) -> int"""
        return _pycudd.DdNode_SupportSize(self)

    def Density(self, *args):
        """Density(DdNode self, int nvars) -> double"""
        return _pycudd.DdNode_Density(self, *args)

    def NodeReadIndex(self):
        """NodeReadIndex(DdNode self) -> int"""
        return _pycudd.DdNode_NodeReadIndex(self)

    def IsNonConstant(self):
        """IsNonConstant(DdNode self) -> int"""
        return _pycudd.DdNode_IsNonConstant(self)

    def DagSize(self):
        """DagSize(DdNode self) -> int"""
        return _pycudd.DdNode_DagSize(self)

    def EstimateCofactorSimple(self, *args):
        """EstimateCofactorSimple(DdNode self, int i) -> int"""
        return _pycudd.DdNode_EstimateCofactorSimple(self, *args)

    def CountPath(self):
        """CountPath(DdNode self) -> double"""
        return _pycudd.DdNode_CountPath(self)

    def CountLeaves(self):
        """CountLeaves(DdNode self) -> int"""
        return _pycudd.DdNode_CountLeaves(self)

    def BddStore(self, *args):
        """
        BddStore(DdNode self, char * ddname, char ** varnames, IntArray auxids, int mode, int varinfo, char * fname, 
            FILE * fp) -> int
        """
        return _pycudd.DdNode_BddStore(self, *args)

    def IsConstant(self):
        """IsConstant(DdNode self) -> int"""
        return _pycudd.DdNode_IsConstant(self)

    def Not(self):
        """Not(DdNode self) -> DdNode"""
        return _pycudd.DdNode_Not(self)

    def NotCond(self, *args):
        """NotCond(DdNode self, int c) -> DdNode"""
        return _pycudd.DdNode_NotCond(self, *args)

    def Regular(self):
        """Regular(DdNode self) -> DdNode"""
        return _pycudd.DdNode_Regular(self)

    def Complement(self):
        """Complement(DdNode self) -> DdNode"""
        return _pycudd.DdNode_Complement(self)

    def IsComplement(self):
        """IsComplement(DdNode self) -> int"""
        return _pycudd.DdNode_IsComplement(self)

    def T(self):
        """T(DdNode self) -> DdNode"""
        return _pycudd.DdNode_T(self)

    def E(self):
        """E(DdNode self) -> DdNode"""
        return _pycudd.DdNode_E(self)

    def V(self):
        """V(DdNode self) -> double"""
        return _pycudd.DdNode_V(self)

    def ReadIndex(self, *args):
        """ReadIndex(DdNode self, int index) -> int"""
        return _pycudd.DdNode_ReadIndex(self, *args)

    def addExistAbstract(self, *args):
        """addExistAbstract(DdNode self, DdNode cube) -> DdNode"""
        return _pycudd.DdNode_addExistAbstract(self, *args)

    def addUnivAbstract(self, *args):
        """addUnivAbstract(DdNode self, DdNode cube) -> DdNode"""
        return _pycudd.DdNode_addUnivAbstract(self, *args)

    def addOrAbstract(self, *args):
        """addOrAbstract(DdNode self, DdNode cube) -> DdNode"""
        return _pycudd.DdNode_addOrAbstract(self, *args)

    def addFindMax(self):
        """addFindMax(DdNode self) -> DdNode"""
        return _pycudd.DdNode_addFindMax(self)

    def addFindMin(self):
        """addFindMin(DdNode self) -> DdNode"""
        return _pycudd.DdNode_addFindMin(self)

    def addIthBit(self, *args):
        """addIthBit(DdNode self, int bit) -> DdNode"""
        return _pycudd.DdNode_addIthBit(self, *args)

    def addScalarInverse(self, *args):
        """addScalarInverse(DdNode self, DdNode epsilon) -> DdNode"""
        return _pycudd.DdNode_addScalarInverse(self, *args)

    def addIte(self, *args):
        """addIte(DdNode self, DdNode g, DdNode h) -> DdNode"""
        return _pycudd.DdNode_addIte(self, *args)

    def addIteConstant(self, *args):
        """addIteConstant(DdNode self, DdNode g, DdNode h) -> DdNode"""
        return _pycudd.DdNode_addIteConstant(self, *args)

    def addEvalConst(self, *args):
        """addEvalConst(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_addEvalConst(self, *args)

    def addLeq(self, *args):
        """addLeq(DdNode self, DdNode g) -> int"""
        return _pycudd.DdNode_addLeq(self, *args)

    def addCmpl(self):
        """addCmpl(DdNode self) -> DdNode"""
        return _pycudd.DdNode_addCmpl(self)

    def addNegate(self):
        """addNegate(DdNode self) -> DdNode"""
        return _pycudd.DdNode_addNegate(self)

    def addRoundOff(self, *args):
        """addRoundOff(DdNode self, int N) -> DdNode"""
        return _pycudd.DdNode_addRoundOff(self, *args)

    def addCompose(self, *args):
        """addCompose(DdNode self, DdNode g, int v) -> DdNode"""
        return _pycudd.DdNode_addCompose(self, *args)

    def addPermute(self, *args):
        """addPermute(DdNode self, IntArray permut) -> DdNode"""
        return _pycudd.DdNode_addPermute(self, *args)

    def addConstrain(self, *args):
        """addConstrain(DdNode self, DdNode c) -> DdNode"""
        return _pycudd.DdNode_addConstrain(self, *args)

    def addRestrict(self, *args):
        """addRestrict(DdNode self, DdNode c) -> DdNode"""
        return _pycudd.DdNode_addRestrict(self, *args)

    def addMatrixMultiply(self, *args):
        """addMatrixMultiply(DdNode self, DdNode B, DdArray z, int nz) -> DdNode"""
        return _pycudd.DdNode_addMatrixMultiply(self, *args)

    def addTimesPlus(self, *args):
        """addTimesPlus(DdNode self, DdNode B, DdArray z, int nz) -> DdNode"""
        return _pycudd.DdNode_addTimesPlus(self, *args)

    def addTriangle(self, *args):
        """addTriangle(DdNode self, DdNode g, DdArray z, int nz) -> DdNode"""
        return _pycudd.DdNode_addTriangle(self, *args)

    def addVectorCompose(self, *args):
        """addVectorCompose(DdNode self, DdArray vector) -> DdNode"""
        return _pycudd.DdNode_addVectorCompose(self, *args)

    def addNonSimCompose(self, *args):
        """addNonSimCompose(DdNode self, DdArray vector) -> DdNode"""
        return _pycudd.DdNode_addNonSimCompose(self, *args)

    def addSwapVariables(self, *args):
        """addSwapVariables(DdNode self, DdArray x, DdArray y, int n) -> DdNode"""
        return _pycudd.DdNode_addSwapVariables(self, *args)

    def zddProduct(self, *args):
        """zddProduct(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_zddProduct(self, *args)

    def zddUnateProduct(self, *args):
        """zddUnateProduct(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_zddUnateProduct(self, *args)

    def zddWeakDiv(self, *args):
        """zddWeakDiv(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_zddWeakDiv(self, *args)

    def zddDivide(self, *args):
        """zddDivide(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_zddDivide(self, *args)

    def zddWeakDivF(self, *args):
        """zddWeakDivF(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_zddWeakDivF(self, *args)

    def zddDivideF(self, *args):
        """zddDivideF(DdNode self, DdNode g) -> DdNode"""
        return _pycudd.DdNode_zddDivideF(self, *args)

    def zddComplement(self):
        """zddComplement(DdNode self) -> DdNode"""
        return _pycudd.DdNode_zddComplement(self)

    def zddIte(self, *args):
        """zddIte(DdNode self, DdNode g, DdNode h) -> DdNode"""
        return _pycudd.DdNode_zddIte(self, *args)

    def zddUnion(self, *args):
        """zddUnion(DdNode self, DdNode Q) -> DdNode"""
        return _pycudd.DdNode_zddUnion(self, *args)

    def zddIntersect(self, *args):
        """zddIntersect(DdNode self, DdNode Q) -> DdNode"""
        return _pycudd.DdNode_zddIntersect(self, *args)

    def zddDiff(self, *args):
        """zddDiff(DdNode self, DdNode Q) -> DdNode"""
        return _pycudd.DdNode_zddDiff(self, *args)

    def zddDiffConst(self, *args):
        """zddDiffConst(DdNode self, DdNode Q) -> DdNode"""
        return _pycudd.DdNode_zddDiffConst(self, *args)

    def zddSubset1(self, *args):
        """zddSubset1(DdNode self, int var) -> DdNode"""
        return _pycudd.DdNode_zddSubset1(self, *args)

    def zddSubset0(self, *args):
        """zddSubset0(DdNode self, int var) -> DdNode"""
        return _pycudd.DdNode_zddSubset0(self, *args)

    def zddChange(self, *args):
        """zddChange(DdNode self, int var) -> DdNode"""
        return _pycudd.DdNode_zddChange(self, *args)

    def zddCount(self):
        """zddCount(DdNode self) -> int"""
        return _pycudd.DdNode_zddCount(self)

    def zddCountDouble(self):
        """zddCountDouble(DdNode self) -> double"""
        return _pycudd.DdNode_zddCountDouble(self)

    def zddPrintMinterm(self):
        """zddPrintMinterm(DdNode self) -> int"""
        return _pycudd.DdNode_zddPrintMinterm(self)

    def zddPrintCover(self):
        """zddPrintCover(DdNode self) -> int"""
        return _pycudd.DdNode_zddPrintCover(self)

    def zddPrintDebug(self, *args):
        """zddPrintDebug(DdNode self, int n, int pr) -> int"""
        return _pycudd.DdNode_zddPrintDebug(self, *args)

    def zddCountMinterm(self, *args):
        """zddCountMinterm(DdNode self, int path) -> double"""
        return _pycudd.DdNode_zddCountMinterm(self, *args)

    def zddIsop(self, *args):
        """zddIsop(DdNode self, DdNode U, DdArray zdd_I) -> DdNode"""
        return _pycudd.DdNode_zddIsop(self, *args)

    def zddDagSize(self, *args):
        """zddDagSize(DdNode self, DdNode p_node) -> int"""
        return _pycudd.DdNode_zddDagSize(self, *args)

    def ApaPrintMinterm(self, *args):
        """ApaPrintMinterm(DdNode self, FILE * fp, int nvars) -> int"""
        return _pycudd.DdNode_ApaPrintMinterm(self, *args)

    def ApaPrintMintermExp(self, *args):
        """ApaPrintMintermExp(DdNode self, FILE * fp, int nvars, int precision) -> int"""
        return _pycudd.DdNode_ApaPrintMintermExp(self, *args)

    def ApaPrintDensity(self, *args):
        """ApaPrintDensity(DdNode self, FILE * fp, int nvars) -> int"""
        return _pycudd.DdNode_ApaPrintDensity(self, *args)

    def ApaCountMinterm(self, *args):
        """ApaCountMinterm(DdNode self, int nvars, IntArray digits) -> DdApaNumber"""
        return _pycudd.DdNode_ApaCountMinterm(self, *args)

    def __hash__(self):
        """__hash__(DdNode self) -> int"""
        return _pycudd.DdNode___hash__(self)

    def __int__(self):
        """__int__(DdNode self) -> int"""
        return _pycudd.DdNode___int__(self)

    def __and__(self, *args):
        """__and__(DdNode self, DdNode other) -> DdNode"""
        return _pycudd.DdNode___and__(self, *args)

    def __or__(self, *args):
        """__or__(DdNode self, DdNode other) -> DdNode"""
        return _pycudd.DdNode___or__(self, *args)

    def __xor__(self, *args):
        """__xor__(DdNode self, DdNode other) -> DdNode"""
        return _pycudd.DdNode___xor__(self, *args)

    def __invert__(self):
        """__invert__(DdNode self) -> DdNode"""
        return _pycudd.DdNode___invert__(self)

    def __rshift__(self, *args):
        """__rshift__(DdNode self, DdNode other) -> DdNode"""
        return _pycudd.DdNode___rshift__(self, *args)

    def __cmp__(self, *args):
        """__cmp__(DdNode self, DdNode other) -> bool"""
        return _pycudd.DdNode___cmp__(self, *args)

    def __sub__(self, *args):
        """__sub__(DdNode self, DdNode other) -> DdNode"""
        return _pycudd.DdNode___sub__(self, *args)

    def __add__(self, *args):
        """__add__(DdNode self, DdNode other) -> DdNode"""
        return _pycudd.DdNode___add__(self, *args)

    def __lt__(self, *args):
        """__lt__(DdNode self, DdNode other) -> bool"""
        return _pycudd.DdNode___lt__(self, *args)

    def __le__(self, *args):
        """__le__(DdNode self, DdNode other) -> bool"""
        return _pycudd.DdNode___le__(self, *args)

    def __eq__(self, *args):
        """__eq__(DdNode self, DdNode other) -> bool"""
        return _pycudd.DdNode___eq__(self, *args)

    def __ne__(self, *args):
        """__ne__(DdNode self, DdNode other) -> bool"""
        return _pycudd.DdNode___ne__(self, *args)

    def __gt__(self, *args):
        """__gt__(DdNode self, DdNode other) -> bool"""
        return _pycudd.DdNode___gt__(self, *args)

    def __ge__(self, *args):
        """__ge__(DdNode self, DdNode other) -> bool"""
        return _pycudd.DdNode___ge__(self, *args)

    def __nonzero__(self):
        """__nonzero__(DdNode self) -> bool"""
        return _pycudd.DdNode___nonzero__(self)

    def __len__(self):
        """__len__(DdNode self) -> int"""
        return _pycudd.DdNode___len__(self)

    def SizeOf(self):
        """SizeOf(DdNode self) -> int"""
        return _pycudd.DdNode_SizeOf(self)

    def Show(self, *args):
        """Show(DdNode self, char * name, int op1, int op2)"""
        return _pycudd.DdNode_Show(self, *args)

    def Empty(self):
        """Empty(DdNode self) -> bool"""
        return _pycudd.DdNode_Empty(self)

    def DumpDot(self):
        """DumpDot(DdNode self) -> int"""
        return _pycudd.DdNode_DumpDot(self)

    def DumpBlif(self):
        """DumpBlif(DdNode self) -> int"""
        return _pycudd.DdNode_DumpBlif(self)

    def Vector(self):
        """Vector(DdNode self) -> DdArray"""
        return _pycudd.DdNode_Vector(self)

DdNode_swigregister = _pycudd.DdNode_swigregister
DdNode_swigregister(DdNode)

class NodePair(_object):
    """Proxy of C++ NodePair class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, NodePair, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NodePair, name)
    __repr__ = _swig_repr
    def __iter__(self):
      global iter_meth
      if iter_meth != 2:
        print "Can only enumerate primes for a NodePair. Setting iter_meth == 2 and proceeding"
        iter_meth == 2
      return ForeachPrimeIterator(self)
    __doc__="This is used to provide the functionality of prime enumeration in CUDD 2.4.0. Create the NodePair by passing the DdNodes for lower and upper to the constructor. Once that is done, you can iterate over the primes of the NodePair using the Python for statement. There is no need to do this if you are interested in the primes of a simple DdNode -- the package automatically creates the NodePair and destroys it in that case."


    def __init__(self, *args): 
        """__init__(NodePair self, DdNode lwr, DdNode upr) -> NodePair"""
        this = _pycudd.new_NodePair(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pycudd.delete_NodePair
    __del__ = lambda self : None;
    def LOWER(self):
        """LOWER(NodePair self) -> DdNode"""
        return _pycudd.NodePair_LOWER(self)

    def UPPER(self):
        """UPPER(NodePair self) -> DdNode"""
        return _pycudd.NodePair_UPPER(self)

    def FirstPrime(self, *args):
        """FirstPrime(NodePair self, DdGen gen) -> int"""
        return _pycudd.NodePair_FirstPrime(self, *args)

    def NextPrime(self, *args):
        """NextPrime(NodePair self, DdGen gen) -> int"""
        return _pycudd.NodePair_NextPrime(self, *args)

NodePair_swigregister = _pycudd.NodePair_swigregister
NodePair_swigregister(NodePair)

cudd_version = 0x020400

###############################
#
# iter_meth is used to set, surprise, the iteration method for DdNodes
# 0 -- over cubes
# 1 -- over nodes
# 2 -- over primes
# Note that iteration over primes is only available in CUDD >= 2.4.0
#
################################
iter_meth = 0

def set_iter_meth(meth,verbose = False):
  global iter_meth
  methods = ["cubes", "nodes", "primes"]
  if verbose:
      print "Setting iter method to iterate over ",methods[meth]
  iter_meth = meth

class ForeachCubeIterator:
    def __init__(self,Dd):
        self.gen = DdGen(Dd,iter_meth)
        self.node = Dd
        self.done = 0
        self.ret_val = Dd.FirstCube(self.gen)
        if not self.ret_val[0]: self.done = 1
        
    def __iter__(self):
        return self

    def next(self):
        if self.done: raise StopIteration
        to_ret = self.ret_val[1:]
        self.ret_val = self.node.NextCube(self.gen)
        if not self.ret_val[0]:
	    self.done = 1
        return to_ret

class ForeachNodeIterator:
    def __init__(self,Dd):
        self.gen = DdGen(Dd,iter_meth)
        self.node = Dd
        self.done = 0
        self.ret_val = Dd.FirstNode(self.gen)
        if not self.ret_val[0]: self.done = 1
        
    def __iter__(self):
        return self

    def next(self):
        if self.done: raise StopIteration
        to_ret = self.ret_val[1]
        self.ret_val = self.node.NextNode(self.gen)
        if not self.ret_val[0]:
            self.done = 1
        return to_ret

class ForeachPrimeIterator:
    def __init__(self,npair):
        global cudd_version
        if cudd_version < 0x020400:
            print "CUDD versions < 2.4.0 do not support iteration over primes"
            raise RuntimeError
        self.gen = DdGen(npair.LOWER(), iter_meth, npair.UPPER())
        self.npair = npair
        self.done = 0
        self.ret_val = npair.FirstPrime(self.gen)
        if not self.ret_val[0]: self.done = 1
    def __iter__(self):
        return self

    def next(self):
        if self.done: raise StopIteration
        to_ret = self.ret_val[1:]
        self.ret_val = self.npair.NextPrime(self.gen)
	if not self.ret_val[0]:
            self.done = 1
        return to_ret

def cube_tuple_to_str(cube_tup):
    res = ""
    for char in cube_tup:
        if char == 2: res += '-'
        else: res += str(char)
    return res

# This file is compatible with both classic and new-style classes.


